from kit_common import *
GRA=('Treccani — Analisi grammaticale','https://www.treccani.it/enciclopedia/analisi-grammaticale_(La-grammatica-italiana)/')
LOG=('Treccani — Analisi logica','https://www.treccani.it/enciclopedia/analisi-logica_(Enciclopedia-dell%27Italiano)/')
SOG=('Treccani — Soggetto e accordo','https://www.treccani.it/enciclopedia/soggetto_(Enciclopedia-dell%27Italiano)/')
FRA=('OpenStax, Prealgebra 2e — cap. 4, frazioni','https://openstax.org/books/prealgebra-2e/pages/4-4-add-and-subtract-fractions-with-common-denominators')
ALG=('OpenStax, Prealgebra 2e — §2.1, espressioni','https://openstax.org/books/prealgebra-2e/pages/2-1-use-the-language-of-algebra')
D=[]
D+=kit('ITA04','Riconoscere le parti del discorso e descrivere le forme nel contesto','Leggere una frase semplice e riconoscere alcune parole note','Tabella parola–categoria–caratteristiche',[
P('Parole dentro una frase',H('Avvio','In «La luce è accesa» e «La vedo», la parola «la» svolge lo stesso compito? Leggi le frasi intere prima di decidere.'),
TAB(['Categoria','Parola tra parentesi quadre'],[['Articolo','[il] libro'],['Nome','il [libro]'],['Aggettivo','un libro [nuovo]'],['Pronome','[lo] leggo'],['Verbo','noi [leggiamo]'],['Avverbio','leggo [lentamente]'],['Preposizione','un libro [di] storia'],['Congiunzione','leggo [e] scrivo'],['Interiezione','[Oh!] Che sorpresa!']],[5,12.6]),
H('Esempio spiegato','«Le ragazze leggono attentamente». Le: articolo determinativo, femminile plurale; ragazze: nome comune di persona, femminile plurale; leggono: verbo leggere, indicativo presente, terza persona plurale; attentamente: avverbio di modo. La categoria dipende dall’uso nella frase.'),
T('Nomi, articoli, aggettivi, pronomi e verbi sono categorie generalmente variabili. Avverbi, preposizioni, congiunzioni e interiezioni sono tradizionalmente invariabili; esistono anche nomi invariabili come «città».')),
P('Mettere a fuoco il verbo',H('Una scheda essenziale','Per un verbo indica infinito, modo, tempo, persona e numero, quando presenti. «Abbiamo letto»: leggere, indicativo, passato prossimo, prima persona plurale. Ausiliare e participio formano un tempo composto.'),
TAB(['Forma','Modo e tempo'],[['leggeva','indicativo imperfetto'],['leggerà','indicativo futuro semplice'],['che legga','congiuntivo presente'],['leggerebbe','condizionale presente'],['leggi! (ordine a tu)','imperativo presente'],['leggere / leggendo / letto','infinito / gerundio / participio']],[6.2,11.4]),
H('Guidata','Analizza «I miei amici hanno camminato lentamente nel parco». Trova: articolo, aggettivo possessivo, nome, gruppo verbale, avverbio e preposizione articolata. Per il verbo usa la scheda; per le altre parole indica genere e numero solo se pertinenti.'),L(4)),
P('La tua griglia grammaticale',H('Costruisci lo strumento','Crea colonne diverse per nomi e verbi: non tutte le categorie richiedono le stesse informazioni. Usa questa frase: «Questa penna scrive bene; quella è nuova».'),
TAB(['Parola nel contesto','Categoria','Caratteristiche utili'],[['questa','',''],['penna','',''],['scrive','',''],['bene','',''],['quella','','']],[5.2,5.7,6.7]),L(3),
H('Controlla la scelta','«Questa» accompagna penna; «quella» ne prende il posto. Scrivi un esempio personale che distingua aggettivo e pronome. Puoi aggiungere alla griglia un esempio o una domanda guida.')),
P('Analizzare e giustificare',H('Trasferimento','A. «Domani noi porteremo due quaderni a scuola». Analizza domani, noi, porteremo, due, quaderni, a.\nB. «La torta è pronta e io la assaggio». Classifica le due occorrenze di «la» e la parola «e».\nC. Trasforma «Le ragazze leggono» al singolare: quali parole cambiano?'),L(7),
H('Recupero e ripasso','Perché non basta imparare una categoria per ogni parola isolata? Quali informazioni descrivono un tempo composto? In un altro giorno, aggiungi alla tua griglia una frase del libro e controlla con la grammatica scolastica.'))
],[H('Avvio','Nella prima frase «la» è articolo determinativo riferito a luce; nella seconda è pronome personale con funzione di oggetto (terza persona, femminile singolare).'),
H('Guidata','I: articolo determinativo maschile plurale; miei: aggettivo possessivo maschile plurale, possessore prima persona singolare; amici: nome comune di persona maschile plurale; hanno camminato: camminare, prima coniugazione, indicativo passato prossimo, terza persona plurale, attivo, intransitivo; lentamente: avverbio di modo; nel: preposizione articolata in + il; parco: nome comune di cosa maschile singolare.'),
H('Griglia','questa: aggettivo dimostrativo femminile singolare; penna: nome comune femminile singolare; scrive: scrivere, indicativo presente, terza singolare; bene: avverbio di modo; quella: pronome dimostrativo femminile singolare. «È nuova» attribuisce una qualità al referente di quella.'),
H('Trasferimento','A: domani, avverbio di tempo; noi, pronome personale prima plurale; porteremo, portare, indicativo futuro semplice prima plurale; due, aggettivo numerale cardinale invariabile; quaderni, nome comune maschile plurale; a, preposizione semplice. B: prima la articolo, seconda la pronome personale; e congiunzione coordinativa copulativa. C: «La ragazza legge»: cambiano articolo, nome e verbo.')],
'Usare il significato da solo per assegnare la categoria; confondere aggettivo e pronome; chiedere genere e numero a un avverbio; separare ausiliare e participio nell’indicazione del tempo. Concordare con la scuola il grado di dettaglio richiesto.',
[GRA],'Nove categorie, flessione essenziale, aggettivo/pronome, tempi semplici e composti, riconoscimento di modi verbali.','coniugazioni complete, usi avanzati dei modi, tutte le sottoclassi e alterazioni dei nomi.')

D+=kit('ITA05','Analizzare soggetto, predicato e principali relazioni nella frase','Riconoscere il verbo e comprendere chi o che cosa riguarda una frase','Schema della frase e tabella delle relazioni',[
P('Partire dal predicato',H('Avvio','In «Il vetro è stato rotto dal vento», il soggetto è il vento? Controlla con quale elemento concorda il verbo: «I vetri sono stati rotti…».'),
H('Nucleo della frase','Il soggetto è l’elemento cui si riferisce il predicato e con cui questo concorda. Non è sempre chi compie un’azione. Il predicato verbale esprime un’azione o uno stato; nel predicato nominale con essere, la copula collega il soggetto a un nome o a un aggettivo: «La stanza è silenziosa».'),
H('Esempio spiegato','«Oggi Sara presta un libro a Luca». Predicato verbale: presta. Soggetto: Sara. Oggetto: un libro. Destinatario, complemento di termine: a Luca. Tempo determinato: oggi. In «Sara è gentile», è gentile forma il predicato nominale; gentile è la parte nominale.'),
H('Una procedura','Trova il predicato intero. Cerca il soggetto tramite il significato e l’accordo, anche se viene dopo il verbo. Raggruppa poi le parole che svolgono la stessa funzione. Le domande guida aiutano, ma vanno controllate nel contesto.'),
T('«Arrivano i ragazzi»: soggetto i ragazzi. «Leggiamo»: soggetto sottinteso noi. Non attribuire un soggetto a ogni forma impersonale.')),
P('Relazioni frequenti',
TAB(['Relazione','Esempio con il gruppo da analizzare'],[['Oggetto: che cosa riceve l’azione?','Anna apre [la finestra].'],['Termine: a chi è destinato?','Dò il quaderno [a Paolo].'],['Specificazione: di chi / di che cosa?','Il quaderno [di Paolo].'],['Tempo: quando / per quanto?','Arrivo [domani]; studio [per un’ora].'],['Luogo: dove / verso dove?','Resto [in aula]; vado [a casa].'],['Mezzo: mediante che cosa?','Scrivo [con la penna].'],['Causa: per quale motivo?','Tremo [per il freddo].'],['Agente / causa efficiente nel passivo','Letto [da Ada]; piegato [dal vento].']],[8,9.6]),
H('Attività guidata','Analizza «Ieri il giovane Marco ha consegnato una lettera a Sofia». Trova il predicato intero, il soggetto, l’oggetto, il termine e il tempo. Che funzione ha giovane rispetto a Marco?'),L(3)),
P('Costruire lo schema della frase',H('Uno schema da provare','Scrivi al centro il predicato; collega soggetto e altri gruppi con un’etichetta. «Domani Anna porterà il quaderno di Luca a scuola». Mantieni «di Luca» collegato a quaderno, perché lo specifica.'),L(6),
H('Versione lineare','Predicato → soggetto → oggetto → altre relazioni. Un gruppo può contenere una precisazione: oggetto «il quaderno di Luca», con specificazione «di Luca». In analisi logica distingui queste funzioni senza spezzare il significato.'),
H('Attributo e apposizione','L’attributo è un aggettivo riferito a un nome: «la nuova aula». L’apposizione è un nome che precisa un altro nome: «Anna, la rappresentante». Aggiungi allo strumento un tuo esempio di ciascuno.')),
P('Un compito nuovo',H('Trasferimento','1. «La biblioteca è tranquilla». Trova soggetto e predicato.\n2. «Il libro è stato letto da Marta». Trova soggetto, predicato e agente.\n3. «Con la matita Luca disegna un albero sul foglio». Trova mezzo, soggetto, predicato, oggetto e luogo.\n4. «Il quaderno di Elena è sul banco». Distingui soggetto, specificazione, predicato e luogo: qui essere indica trovarsi.'),L(6),
H('Recupero e ripasso','Il soggetto compie sempre l’azione? Essere introduce sempre un predicato nominale? In un giorno diverso, ricostruisci lo schema di una frase nuova e motiva due collegamenti.'))
],[H('Avvio','Il soggetto è il vetro, che subisce l’azione; dal vento è causa efficiente. L’accordo plurale conferma «i vetri sono stati rotti». Non basta chiedere chi compie l’azione.'),
H('Guidata','Ieri: tempo determinato; Marco: soggetto, con articolo il e attributo giovane; ha consegnato: predicato verbale; una lettera: oggetto; a Sofia: termine. Per chiarezza si può prima riconoscere il gruppo «il giovane Marco», poi distinguere l’attributo.'),
H('Schema','Anna: soggetto; porterà: predicato verbale; il quaderno: oggetto; di Luca: specificazione riferita a quaderno; domani: tempo determinato; a scuola: moto a luogo. Esempi personali corretti: «il libro rosso» (rosso attributo); «Luca, il capitano» (capitano apposizione).'),
H('Trasferimento','1. La biblioteca: soggetto; è tranquilla: predicato nominale.\n2. Il libro: soggetto; è stato letto: predicato verbale passivo; da Marta: agente.\n3. Con la matita: mezzo; Luca: soggetto; disegna: predicato verbale; un albero: oggetto; sul foglio: stato in luogo.\n4. Il quaderno: soggetto; di Elena: specificazione; è: predicato verbale nel senso di si trova; sul banco: stato in luogo.'),
H('Limite delle etichette','Le domande non identificano sempre una sola funzione. Confrontare le convenzioni della grammatica scolastica, soprattutto per verbi copulativi diversi da essere.')],
'Scegliere come soggetto il primo nome o l’agente; chiamare nominale ogni predicato con essere, anche passivo; confondere oggetto e termine; attribuire una funzione dalla sola preposizione. Chiedere il significato prima dell’etichetta.',
[LOG,SOG],'Soggetto e accordo, predicato verbale/nominale con essere, passivo, attributo/apposizione e otto relazioni frequenti.','tutti i complementi tradizionali, frasi ambigue e analisi valenziale estesa.')

D+=kit('MAT01','Confrontare numeri e operare con frazioni spiegando i passaggi','Moltiplicazioni e divisioni, anche con tavola o calcolatrice','Striscia delle frazioni e scheda delle operazioni',[
P('Che cosa rappresenta una frazione',H('Avvio','Disegna due rettangoli uguali. Dividine uno in due parti uguali e l’altro in quattro. Colora 1/2 nel primo e 2/4 nel secondo: quanto spazio è colorato?'),
H('Contenuto essenziale','In 3/4 il denominatore 4 indica in quante parti uguali è divisa l’unità; il numeratore 3 quante ne consideriamo. La frazione rappresenta anche 3 diviso 4. Il denominatore non può essere zero. Una frazione può essere maggiore di 1: 5/4 = 1 + 1/4.'),
H('Equivalenza e confronto · esempio','3/4 = 6/8: moltiplico numeratore e denominatore per 2. Per confrontare 3/4 e 5/8, uso 6/8 e 5/8: 3/4 è maggiore. Per ridurre 6/8, divido entrambi i termini per 2 e ottengo 3/4.'),
H('Prova guidata','A. Completa 2/3 = …/12. B. Riduci 10/15. C. Confronta 5/6 e 3/4 usando dodicesimi. Disegna se ti aiuta.'),L(5)),
P('Operazioni con le frazioni',
TAB(['Operazione','Esempio spiegato'],[['Somma e differenza','1/3 + 1/4 = 4/12 + 3/12 = 7/12.\n5/6 − 1/3 = 5/6 − 2/6 = 3/6 = 1/2.'],['Prodotto','2/3 × 3/5 = 6/15 = 2/5. Moltiplico i numeratori e i denominatori.'],['Divisione','3/4 : 2/5 = 3/4 × 5/2 = 15/8. Moltiplico per il reciproco del divisore, che deve essere diverso da zero.']],[4.6,13]),
H('Frazione di una quantità','Per trovare 3/4 di 20 figurine calcolo 20 : 4 × 3 = 15 figurine. Controllo: il risultato è minore di 20 perché 3/4 è minore di 1.'),
H('Guidata','D. 2/5 + 1/10 = …/10 + 1/10 = …\nE. 7/8 − 1/4 = …\nF. 3/5 × 10/9 = …\nG. 2/3 : 4/5 = …\nH. Calcola 2/3 di 18 oggetti.'),L(4)),
P('Numeri sulla retta',H('Interi e decimali','Sulla retta i numeri aumentano verso destra. Quindi −3 è minore di −1, anche se 3 è maggiore di 1. Da −3, aggiungere 5 porta a 2: attraverso lo zero. Sottrarre un numero equivale ad aggiungere il suo opposto: 2 − (−3) = 2 + 3 = 5.'),
H('Segni e operazioni','Prodotto o quoziente di due numeri con lo stesso segno: positivo; con segni diversi: negativo. Esempi: (−2) × (−4) = 8; (−12) : 3 = −4. Queste regole non sostituiscono quelle della somma.'),
H('Dalla frazione al decimale','3/4 = 3 : 4 = 0,75. Un decimale limitato può diventare frazione: 0,6 = 6/10 = 3/5. Non arrotondare senza dichiararlo: 1/3 = 0,333… non è esattamente 0,33.'),
H('Guidata','I. Ordina da minore a maggiore: −2; 0,5; −0,5; 0.\nJ. Calcola −4 + 7; −2 − 3; (−3) × 5; (−12) : (−4).\nK. Scrivi 0,25 come frazione ridotta.'),L(5)),
P('Costruire un promemoria utile',H('La tua scheda','Prepara una riga per ogni operazione. Riporta la regola con un esempio tuo e un controllo del risultato. Per somme e differenze scrivi perché servono parti della stessa grandezza.'),
TAB(['Compito','Passaggi e controllo'],[['Confrontare frazioni',''],['Somma / differenza',''],['Prodotto / divisione',''],['Frazione di una quantità','']],[6,11.6]),L(3),
H('Provala prima di usarla','Un compagno propone 1/2 + 1/3 = 2/5. Usa la tua scheda per trovare l’errore e correggerlo. Aggiungi un avviso sul denominatore zero e sul divisore zero. Puoi affiancare una retta numerica disegnata da te.')),
P('Trasferire e controllare',H('Nuovi compiti','1. Un nastro è lungo 3/4 m; ne usi 1/6 m. Quanto resta?\n2. Calcola 5/6 : 2/3. Prima prevedi se il risultato supera 1.\n3. Trova 3/5 di 25 biglietti.\n4. La temperatura passa da −2 °C a 4 °C. Di quanti gradi aumenta?\n5. Ordina: 2/3; 0,5; 3/4. Usa frazioni o decimali senza arrotondamenti ingannevoli.'),L(6),
H('Recupero e ripasso','Perché nella somma non si sommano i denominatori? Dividere può aumentare un numero positivo? Spiega con l’esempio 2. In un altro giorno riprova due esercizi cambiando i dati; conserva lo strumento e controlla la soluzione.'))
],[H('Frazioni: avvio e guidata','1/2 e 2/4 colorano la stessa metà di unità uguali. A 8/12; B 2/3; C 5/6 = 10/12 > 9/12 = 3/4. D 4/10 + 1/10 = 5/10 = 1/2; E 7/8 − 2/8 = 5/8; F 30/45 = 2/3; G 2/3 × 5/4 = 10/12 = 5/6; H 18 : 3 × 2 = 12 oggetti.'),
H('Numeri e strumento','I −2 < −0,5 < 0 < 0,5. J 3; −5; −15; 3. K 25/100 = 1/4. Nella scheda: 1/2 + 1/3 = 3/6 + 2/6 = 5/6. Non si possono sommare direttamente mezzi e terzi come se avessero la stessa grandezza; il denominatore identifica l’unità frazionaria.'),
H('Trasferimento','1. 3/4 − 1/6 = 9/12 − 2/12 = 7/12 m.\n2. 5/6 × 3/2 = 15/12 = 5/4 = 1,25. Supera 1 perché 5/6 > 2/3: il dividendo contiene più di una volta il divisore.\n3. 25 : 5 × 3 = 15 biglietti.\n4. 4 − (−2) = 6 °C di aumento.\n5. 0,5 = 1/2 < 2/3 < 3/4: ad esempio 6/12 < 8/12 < 9/12.'),
H('Controllo','Distinguere errore nella scelta dell’operazione, nella trasformazione e nel calcolo. La calcolatrice può verificare un valore, ma chiedere comunque quale quantità e quale unità rappresenti.')],
'Cambiare solo il denominatore; confrontare frazioni guardando solo i numeratori; sommare i denominatori; invertire il dividendo nella divisione; applicare alla somma la regola dei segni del prodotto. Usare unità uguali nei disegni.',
[FRA,ALG],'Frazioni equivalenti e quattro operazioni, quantità, confronti, interi con segno e conversioni decimali limitate.','algoritmi completi di divisibilità, numeri periodici con frazione generatrice e problemi a più vincoli.')

D+=kit('MAT02','Calcolare espressioni rispettando precedenze, potenze e radici','Quattro operazioni e significato dei numeri con segno','Schema delle precedenze e formulario con condizioni',[
P('Scegliere il primo passaggio',H('Avvio','2 + 3 × 4 vale 20 o 14? Indica quale operazione scegli per prima e perché.'),
H('Ordine delle operazioni','Lavora prima dentro le parentesi, dalle più interne. In ogni gruppo calcola potenze e radici; poi moltiplicazioni e divisioni da sinistra a destra; infine somme e differenze da sinistra a destra. Il segno davanti a una potenza richiede attenzione alle parentesi.'),
H('Esempio svolto','18 − 2 × (3 + 1)² : 4\n= 18 − 2 × 4² : 4\n= 18 − 2 × 16 : 4\n= 18 − 32 : 4\n= 18 − 8 = 10'),
T('Ogni riga conserva lo stesso valore. Non leggere «prima tutte le moltiplicazioni, poi tutte le divisioni»: hanno la stessa precedenza.'),
H('Guidata','A. 24 : 3 × 2 = … × 2 = …\nB. 5 + 2 × (7 − 4) = …\nC. (5 + 2) × (7 − 4) = …'),L(4)),
P('Potenze: significato e regole',H('Un prodotto ripetuto','3⁴ = 3 × 3 × 3 × 3 = 81. La base è 3, l’esponente è 4. Per base diversa da zero, a⁰ = 1. In questo kit gli esponenti sono interi non negativi.'),
TAB(['Stessa base o potenza','Esempio'],[['Prodotto: sommo gli esponenti','2³ × 2² = 2⁵ = 32'],['Quoziente: sottraggo gli esponenti','5⁴ : 5² = 5² = 25 (base ≠ 0)'],['Potenza di potenza: moltiplico','(3²)³ = 3⁶ = 729'],['Potenza di un prodotto','(2 × 3)² = 2² × 3² = 36']],[10,7.6]),
H('Un errore da smontare','(2 + 3)² = 25, mentre 2² + 3² = 13. La potenza non si distribuisce sulla somma. Inoltre (−3)² = 9, ma −3² = −9: nel secondo caso il meno è fuori dalla potenza.'),
H('Guidata','D. 2⁴ × 2³ = …\nE. 7³ : 7² = …\nF. (2²)³ = …\nG. Confronta (−2)⁴ e −2⁴.'),L(3)),
P('Radice quadrata e controllo',H('Significato','La radice quadrata di un numero non negativo è il numero non negativo che, elevato al quadrato, dà quel numero. √49 = 7 perché 7² = 49. L’equazione x² = 49 ha invece due soluzioni: 7 e −7.'),
H('Esempio esatto e stima','√81 = 9. Per √20: 4² = 16 e 5² = 25, quindi 4 < √20 < 5. Con la calcolatrice ottengo circa 4,472; scrivo √20 ≈ 4,47 se arrotondo ai centesimi.'),
H('Guidata','H. √64 = …; verifica con una potenza.\nI. Fra quali interi consecutivi si trova √30?\nJ. È vero che √(9 + 16) = √9 + √16? Calcola i due membri.\nK. Nel campo dei numeri reali, √(−4) esiste? Motiva con il segno di un quadrato.'),L(6),
T('Il simbolo ≈ segnala un’approssimazione. Non sostituirlo con = quando il valore è arrotondato.')),
P('Costruire la scheda di controllo',H('Un promemoria a due parti','Parte 1: disegna la sequenza parentesi → potenze/radici → prodotti/divisioni → somme/differenze. Indica «da sinistra a destra» dove serve. Parte 2: scrivi tre regole sulle potenze con un esempio e le condizioni.'),L(6),
H('Collaudo','Usa la scheda per calcolare 30 − 12 : 3 × 2. Poi aggiungi un avviso che distingua (−a)² e −a². Se ti serve, inserisci i quadrati da 1² a 10² e il significato della radice.'),L(3),
T('Conserva la scheda anche quando diminuisce l’aiuto del tutor. La prova serve a verificare se trovi e applichi la regola corretta.')),
P('Espressioni nuove',H('Trasferimento','1. 40 − 3 × (2 + 1)² = …\n2. 3² × 3³ : 3⁴ = …\n3. √144 + 2³ = …\n4. (−4)² − √25 = …\n5. Fra quali interi si trova √50? Arrotondala ai centesimi con la calcolatrice, indicando l’approssimazione.'),L(7),
H('Recupero e ripasso','Spiega perché 24 : 3 × 2 non equivale a 24 : (3 × 2). Qual è la differenza tra √36 e le soluzioni di x² = 36? In un giorno diverso, riprova un’espressione e una stima usando la tua scheda.'))
],[H('Precedenze','Avvio 14. A 24 : 3 × 2 = 8 × 2 = 16; B 11; C 21. L’esempio 18 − 2 × 16 : 4 vale 10. Confronto finale: 24 : (3 × 2) vale 4.'),
H('Potenze','D 2⁷ = 128; E 7¹ = 7; F 2⁶ = 64; G (−2)⁴ = 16, mentre −2⁴ = −16. Nell’esempio (3²)³ = 729; 2² + 3² = 13 non coincide con (2 + 3)² = 25.'),
H('Radici','H √64 = 8 e 8² = 64. I 5 < √30 < 6 perché 25 < 30 < 36. J √25 = 5, mentre 3 + 4 = 7: l’uguaglianza è falsa. K Non esiste una radice quadrata reale di −4 perché ogni quadrato reale è non negativo.'),
H('Strumento e trasferimento','Collaudo: 30 − 12 : 3 × 2 = 30 − 4 × 2 = 22.\n1. 40 − 3 × 9 = 13.\n2. 3^(2+3−4) = 3.\n3. 12 + 8 = 20.\n4. 16 − 5 = 11.\n5. 7 < √50 < 8; √50 ≈ 7,07.\nRecupero: √36 = 6; x² = 36 ha soluzioni x = 6 e x = −6.'),
H('Uso delle unità','Queste espressioni sono numeriche e senza unità fisiche. Quando si applicano a misure, controllare anche la coerenza delle unità; il calcolo corretto da solo non garantisce un modello corretto.')],
'Eseguire sempre da sinistra senza precedenze; moltiplicare base ed esponente; usare regole di prodotto per una somma; dimenticare le parentesi dei numeri negativi; dare alla radice principale due segni; confondere uguaglianza e approssimazione.',
[ALG,('OpenStax, Prealgebra 2e — indice, potenze e radici','https://openstax.org/books/prealgebra-2e/pages/index')],'Precedenze, potenze con esponenti non negativi, quattro proprietà, radice principale e stima.','esponenti negativi, notazione scientifica, radicali algebrici e radici di indice diverso da due.')
save('L02-grammatica-numeri',D)
