from crea_trasversali import doc,p,H,L,write_json,MAINT,IES,LOCAL
docs=[]
area='Modelli riutilizzabili'
for minutes,times in [(60,[5,8,15,5,17,7,3]),(90,[8,12,22,7,25,11,5])]:
    labels=['Accoglienza e scelta del compito','Recupero breve e obiettivo','Esempio e pratica guidata','Pausa concordata','Costruzione e prova dello strumento','Nuovo compito e controllo','Chiusura e prossimo passo']
    assert sum(times)==minutes
    rows=[[str(t)+' min',label] for t,label in zip(times,labels)]
    docs.append(doc('IN'+str(minutes),'Incontro da '+str(minutes)+' minuti',area,'Tutor','Preparare e adattare l’incontro',[
      p('Incontro da '+str(minutes)+' minuti',H('Prima dell’incontro','Scegli un compito reale, un obiettivo osservabile e una risorsa del catalogo. Prepara PDF, sorgente, fogli e supporti abituali. Controlla i prerequisiti con una domanda breve.'),dict(table=dict(headers=['Durata indicativa','Attività'],rows=rows,widths=[3.5,14.1])),H('Adatta la scaletta','I tempi sono un esempio. Se serve più comprensione, riduci la quantità del nuovo compito. Concorda le pause e la ripresa; non togliere il supporto utile.'),H('Chiusura','Lo studente indica che cosa sa fare, che cosa lo aiuta e un piccolo passo da provare. Fissa un momento per rivederlo.')),
      p('Preparazione e osservazione',H('Compito e risultato atteso','Materia / argomento: ____________________\nAlla fine lo studente saprà: ____________________'),L(2),H('Materiali e adattamenti','ID risorse: ____________________\nStrumento abituale: ____________________\nAiuto previsto e spazio di scrittura necessario:'),L(2),H('Dopo la prova','Correttezza: ____  Aiuti ricevuti: ____\nUso dello strumento: ____  Tempo indicativo: ____\nFatica riferita dallo studente: ____'),L(2),H('Decisione per il prossimo incontro','Mantengo / cambio: ____________________\nPiccolo passo, quando provarlo e come verificarlo:'),L(2))],sources=IES+'; scaletta e tempi: proposta editoriale originale.',tool='Scaletta incontro',task='Preparare un incontro'))
docs.append(doc('IN-EMO','Avvio, frustrazione, errore e ripresa',area,'Tutor','Sostenere il ritorno al compito senza forzare',[
p('Quando il compito pesa',H('Avvio','Chiedi quale parte sembra affrontabile. Riduci la richiesta al primo passo visibile: leggere la domanda, scegliere un dato o aprire lo strumento. Offri due alternative pratiche.'),H('Frustrazione','Riconosci la fatica con parole semplici: «Questa parte ti sta mettendo in difficoltà». Chiedi che cosa serve: spiegazione diversa, lettura, pausa o meno elementi. Evita ironia, confronto con altri e inviti a calmarsi come condizione per essere aiutati.'),H('Errore','Separa persona e passaggio: «Qui è cambiato il segno; controlliamo questo punto». Mostra come individuare l’errore e prova un caso nuovo. Non correggere tutto nello stesso momento.'),H('Pausa e ripresa','Concorda una pausa breve e una modalità di rientro concreta. Al ritorno riparti dall’ultimo passaggio chiaro. Se il carico resta eccessivo, rivedi il compito anziché insistere sulla stessa richiesta.'),H('Confine educativo','Queste sono routine di accompagnamento al compito. Non includono trattamento di trauma, esposizioni cliniche o valutazioni diagnostiche. Se il disagio persiste, confrontarsi con famiglia e referenti già coinvolti, secondo gli accordi del percorso.')),
p('Una routine da concordare',H('Esempio originale','Durante un problema lo studente dice «non ci riesco» e chiude il quaderno. Il tutor riconosce la fatica, chiede quale passaggio è poco chiaro e propone: «Leggiamo insieme solo la domanda, oppure prima facciamo una pausa». Dopo la scelta si riparte da un passo breve.'),H('Osserva il compito','Situazione e richiesta concreta:'),L(2),H('Ascolta lo studente','Che cosa dice di sentire o di trovare difficile? Evita interpretazioni automatiche.'),L(2),H('Concorda e verifica','Aiuto o pausa scelti: ____________________\nPasso di ripresa: ____________________\nChe cosa è cambiato dopo la prova?'),L(3),H('Fonte e limite','Routine editoriali originali; orientamento dai repertori locali sul compito (Crosera-Perusini, Cappa et al.). Gli adattamenti non sono protocolli clinici validati.'))],sources=LOCAL,tool='Routine educativa',task='Avvio e gestione della fatica'))

# Modelli individuali: nessun caso o dato precompilato.
private='Percorsi individuali/_MODELLO'
forms=[
('P01','Quadro iniziale',[('Compiti e contesto','Codice studente: ______  Data: ______  Classe/coorte: ______\nCompiti scolastici reali, scadenze e richieste della scuola:'),('Risorse','Interessi, competenze, condizioni che aiutano, persone di riferimento:'),('Difficoltà osservate','Descrivi ciò che accade in uno specifico compito. Distingui osservazione del tutor, parole dello studente e informazioni riferite da altri:'),('Strumenti abituali','Strumento, per quale compito, come viene usato, indicazioni già concordate con la scuola:')]),
('P02','Obiettivi e revisione',[('Obiettivo osservabile','Codice: ______  Data di accordo: ______\nCon quale compito e con quali strumenti lo studente farà che cosa?'),('Punto di partenza','Prova iniziale e condizioni: aiuti, correttezza, uso dello strumento, tempo e fatica separati:'),('Criterio e occasione di controllo','Che cosa osserveremo? In quale compito nuovo? Quando?'),('Revisione','Data: ______  Evidenze: ______\nConserviamo, modifichiamo o sostituiamo l’obiettivo? Motivazione e prossimo passo:')]),
('P03','Registro dell’incontro',[('Incontro','Codice: ______  Data: ______  Durata indicativa: ______\nCompito e obiettivo:'),('Materiali','ID e versione della biblioteca; percorso della copia personalizzata; produzioni:'),('Osservazioni separate','Correttezza: ______\nAiuti ricevuti: ______\nUso dello strumento: ______\nTempo indicativo: ______\nFatica riferita e parole dello studente: ______'),('Chiusura','Che cosa ha funzionato? Che cosa cambiare? Piccolo passo successivo, data e modalità di verifica:')]),
('P04','Piano di lavoro e ripassi',[('Piano concordato','Codice: ______  Settimana: ______\nScadenze scolastiche e impegni già presenti:'),('Lavoro disponibile','Giorno, tempo disponibile, compito e primo passo; lasciare un margine:'),('Ripasso','Domande da riprovare, strumenti disponibili, data rivedibile e controllo previsto:'),('Riprogrammazione','Che cosa è stato fatto? Che cosa richiede più tempo o un aiuto diverso? Nuovo accordo:')]),
('P05','Materiali e adattamenti',[('Riferimento','Codice: ______  Data: ______\nID e versione della risorsa generale; obiettivo del compito:'),('Adattamento','Che cosa è cambiato e perché? Testo, numero di elementi, formato, supporto o modalità di risposta:'),('Collocazione','Percorso locale della copia personalizzata e della produzione dello studente. Non inserire questi file nel catalogo generale:'),('Prova d’uso','In quale compito è stato usato? Risultato, aiuti, uso, tempo e fatica separati. Mantenerlo o modificarlo?')]),
('P06','Sintesi periodica',[('Periodo e obiettivi','Codice: ______  Dal: ______  Al: ______\nObiettivi concordati e compiti osservati:'),('Evidenze','Esempi di produzione e condizioni di lavoro. Distinguere correttezza, aiuti, uso dello strumento, tempo indicativo e fatica:'),('Voce dello studente','Che cosa considera più utile? Dove serve ancora aiuto?'),('Decisioni','Obiettivi successivi, adattamenti da mantenere, confronto concordato con scuola/famiglia e prossima revisione:')])]
for id,title,blocks in forms:
    pages=[p(title,*sum(([H(h,t),L(3)] for h,t in blocks),[]))]
    docs.append(doc(id,title,private,'Tutor','Documentare un percorso individuale',pages,private=True,sources='Modello editoriale originale',tool='Scheda individuale'))

EXAM='Preparazione all’esame'
docs.append(doc('ES01','Organizzare la preparazione all’esame',EXAM,'Tutor','Definire un piano coerente con scuola e strumenti abituali',[
p('Preparare l’esame',H('Quadro da verificare','Questa biblioteca prepara abilità e strategie. Le prove del primo ciclo comprendono italiano, competenze logico-matematiche, lingue straniere e colloquio secondo il quadro normativo di riferimento. Il tutor controlla con la scuola le indicazioni applicabili all’anno dell’esame.'),H('DSA e strumenti','Il D.Lgs. 62/2017, art. 11, collega valutazione e prove al PDP e disciplina tempi e strumenti. Il D.M. 741/2017, art. 14, dettaglia lo svolgimento. Non dedurre che una mappa o un dispositivo siano ammessi perché inclusi qui.'),H('Primo passo','Raccogli dalla scuola: tipologie di prova, criteri, strumenti abituali previsti, modalità delle lingue, indicazioni sul colloquio e data dell’ultimo confronto. Se una risposta manca, registrala come da chiarire.'),H('Piano di preparazione','Scegli un nucleo alla volta, prova un esercizio nuovo con il supporto e rivedi ciò che non funziona. Alterna produzione, spiegazione e recupero. I tempi delle simulazioni sono adattabili.'),H('Riferimenti consultati il 29/09/2026','D.Lgs. 62/2017, artt. 8 e 11; D.M. 741/2017, artt. 6-10 e 14. Indicazioni specifiche della scuola non fornite: il modello ES02 serve a raccoglierle.')),
p('Scritti e colloquio',H('Italiano','Leggere consegne e testi; pianificare, scrivere e rivedere. Preparare brevi tracce narrative, descrittive, argomentative e di comprensione/sintesi secondo la scelta della scuola.'),H('Matematica','Riconoscere dati e domanda; scegliere procedura o formula; controllare unità e risultato. Usare i kit su numeri, algebra, geometria, dati e probabilità.'),H('Lingue','Comprendere lo scopo del testo, individuare informazioni e scrivere o parlare in modo pertinente. Non applicare automaticamente le stesse misure a scritto, orale e prove nazionali.'),H('Colloquio','Spiegare conoscenze, ragionare e motivare collegamenti. Un collegamento deve avere un rapporto documentabile; non basta ripetere una parola in materie diverse. La mappa è un possibile supporto, non un formato obbligatorio stabilito qui.'),H('Simulazione e bilancio','Prova una parte selezionata. Osserva contenuto, aiuti, consultazione dello strumento, tempo e fatica separatamente. Concorda una modifica e verifica se aiuta nella prova successiva.'))],sources='D.Lgs. 62/2017 artt. 8,11; D.M. 741/2017 artt. 6-10,14; indicazioni della scuola da raccogliere',tool='Piano esame',task='Preparare l’esame'))
docs.append(doc('ES02','Confronto con la scuola e inventario strumenti',EXAM,'Tutor','Documentare indicazioni e chiarimenti senza presumere autorizzazioni',[
p('Confronto con la scuola',H('Contesto','Codice studente: ______  Classe/coorte: ______\nAnno dell’esame: ______  Data del confronto: ______\nReferente e documento consultato (PDP / indicazioni scuola):'),L(2),H('Informazioni raccolte','Tipologie di prova, criteri e tempi comunicati:'),L(3),H('Strumenti e modalità','Quali supporti sono abituali? In quali prove? Indicazioni ricevute sull’uso all’esame e da chi:'),L(3),H('Questioni aperte','Domande da chiarire, referente, data prevista di risposta:'),L(3),H('Archiviazione','Se compilata per uno studente, salva la scheda nel suo percorso individuale. La copia pubblica deve restare vuota.')),
p('Inventario degli strumenti',H('Per ogni strumento','Codice: ______  Data: ______\nNome e versione dello strumento: ______\nCompito per cui viene utilizzato: ______'),L(2),H('Uso abituale','Esempi e date di utilizzo; grado di familiarità; aiuti necessari:'),L(3),H('Caratteristiche pratiche','Carta / digitale; bisogno di rete, alimentazione o lettore; dimensioni e leggibilità; copia di riserva:'),L(3),H('Indicazioni scolastiche','Indicazione ricevuta: ______\nFonte e data: ______\nAspetti ancora da chiarire: ______'),L(3))],tool='Scheda confronto scuola',sources='Modello editoriale; D.Lgs. 62/2017 art. 11',task='Confrontare strumenti con la scuola'))
docs.append(doc('REL01','Fonti e prospettive: religione o alternativa',area,'Studente','Distinguere fonte, interpretazione e confronto rispettoso',[
p('Leggere due prospettive',H('Obiettivo e avvio','Confrontare il modo in cui due testi motivano un’azione. Prima di leggere chiediti: chi parla, a chi, in quale contesto? Questo modello si adatta ai materiali scelti con il docente.'),H('Esempio originale, non citazione religiosa','Testo A: «Accogliamo chi arriva perché ogni persona merita attenzione». Testo B: «Apriamo uno sportello: chi arriva può informarsi e partecipare». Sono due brevi testi inventati, non rappresentano una religione o un gruppo reale.'),H('Confronto guidato','Entrambi propongono accoglienza. A esplicita un principio; B descrive un’azione e un risultato possibile. Non sappiamo quali altri valori o motivi abbiano gli autori.'),H('Costruisci lo strumento','Su un foglio crea quattro colonne: fonte e contesto; che cosa dice; su che cosa lo sostiene; domande aperte. Inserisci i due testi.'),H('Nuovo compito e ripasso','Usa la tabella per due brevi fonti realmente assegnate. Distingui citazione e tua interpretazione; non attribuire a tutti i membri di un gruppo la posizione di un testo. Al ripasso spiega una convergenza e una differenza.'),L(3))],sources='Testi originali del laboratorio. Fonti disciplinari da scegliere con il docente per la successiva applicazione.',tool='Tabella comparativa',task='Confrontare fonti'))
docs.append(doc('REL01-tutor','Fonti e prospettive - guida',area,'Tutor','Guidare un confronto documentato',[
p('Guida al confronto',H('Criteri di risposta','Nei testi inventati l’azione generale è simile; il primo esplicita un principio, il secondo un’azione concreta e una finalità. Non ricavare una contrapposizione tra persone religiose e non religiose: il testo non fornisce queste informazioni.'),H('Applicazione con fonti reali','Scegli testi brevi pertinenti al programma di religione o attività alternativa. Indica autore/tradizione o istituzione, titolo, data se nota e contesto. Distingui ciò che il testo sostiene da ciò che il lettore ipotizza.'),H('Adattamenti','Leggi o fai ascoltare il testo; riduci il numero delle fonti; prepara le intestazioni della tabella. Conserva possibilità di rispondere oralmente. Non chiedere allo studente di dichiarare credenze personali per completare l’attività.'),H('Controllo e ripasso','Una risposta adeguata cita un elemento di ciascuna fonte, motiva il confronto e indica che cosa non si può concludere. Su una nuova coppia di fonti lo studente adatta la tabella.'),H('Copertura','Modello di lettura e confronto, con esempio completo originale. Non sostituisce contenuti disciplinari, testi sacri o percorsi specifici scelti dal docente.'))],sources='Adattamento editoriale originale',tool='Tabella comparativa',task='Confrontare fonti'))
write_json(MAINT/'produzione/dati/incontri-modelli-esame.json',docs)
print(len(docs),'documenti, incluse sei schede private vuote')
