from kit_common import *

INV=('INVALSIopen — processi di comprensione del testo','https://www.invalsiopen.it/wp-content/uploads/2020/03/LEditoriale-di-INVALSIopen-La-Prova-di-comprensione-del-testo-oltre-l%E2%80%99ora-di-Italiano.pdf')
IES=('IES — organizzare studio, esempi e recupero','https://ies.ed.gov/ncee/wwc/PracticeGuide/1')
PER=('Treccani, La grammatica italiana — Periodo','https://www.treccani.it/enciclopedia/periodo_(La-grammatica-italiana)/')
CON=('Treccani, Enciclopedia dell’Italiano — Congiunzioni','https://www.treccani.it/enciclopedia/congiunzioni_(Enciclopedia-dell%27Italiano)/')
D=[]

D+=kit('ITA01','Distinguere informazione esplicita, inferenza sostenuta e ipotesi non dimostrata','Comprendere una breve sequenza di eventi, anche con lettura ad alta voce','Tabella indizio–conclusione',[
P('Leggere gli indizi',H('Obiettivo e avvio','Spiega da dove viene una risposta. Prima di leggere: se una persona entra con l’ombrello bagnato, puoi essere certo che sia caduta in una fontana? Perché?'),
H('Testo A · Il cartello','Nora arrivò al cancello della piscina con lo zaino. Sul vetro era appeso un foglio: «Oggi impianto chiuso per manutenzione». Guardò l’orologio, prese il telefono e chiamò il padre. Poco dopo si sedette alla fermata dell’autobus.'),
H('Un esempio spiegato','Domanda: perché Nora non entra? Il cartello dichiara che l’impianto è chiuso: è un’informazione esplicita. È plausibile che Nora non sapesse della chiusura, perché arriva con lo zaino e poi chiama. Il testo però non lo dice: è un’inferenza, non una certezza.'),
H('Tre livelli','Esplicito: scritto nel testo. Inferenza: ricostruzione sostenuta da indizi e conoscenze pertinenti. Ipotesi non dimostrata: possibilità per cui mancano indizi sufficienti.'),
T('Regola utile: «Penso che… perché nel testo…; non posso invece concludere che…».')),
P('Rispondere con una prova',H('Attività guidata · usa il testo A','1. Che cosa dice il cartello? Copia solo le parole necessarie.\n2. Il padre viene sicuramente a prendere Nora? Trova ciò che sappiamo e ciò che manca.\n3. La frase «Nora è arrabbiata» è certa, plausibile o priva di indizi sufficienti? Motiva.'),L(5),
H('Testo B · Due informazioni da collegare','La biblioteca presta al massimo tre libri per volta. Paolo ne aveva già due in prestito. Al banco portò altri due libri, ma la bibliotecaria gli chiese di sceglierne soltanto uno.'),
T('4. Perché Paolo può prendere soltanto un altro libro? Collega il limite ai prestiti già attivi. 5. Che cosa potrebbe fare per prendere entrambi i nuovi libri?'),L(3)),
P('Costruire lo strumento',H('La tabella delle prove','Completa una riga per il testo A e una per il testo B. Se la prova non basta, scrivi che cosa resta incerto.'),
TAB(['Domanda','Indizio nel testo','Conclusione e limite'],[['Perché Nora non entra?','',''],['Perché solo un nuovo libro?','',''],['Una mia domanda','','']],[5.3,6.2,6.1]),L(5),
H('Provala e rivedila','Rileggi una tua risposta. L’indizio sostiene proprio quella conclusione? Hai aggiunto emozioni, intenzioni o fatti che il testo non permette di affermare? Aggiungi alla tabella una colonna se ti serve.'),
H('Versione lineare equivalente','Domanda → informazione disponibile → collegamento → risposta → ciò che non sappiamo. Puoi usare queste cinque etichette invece della tabella.')),
P('Un testo nuovo',H('Trasferimento · L’allenamento','L’allenamento era previsto all’aperto. Alle 16 il campo era coperto da grandi pozzanghere. L’allenatrice mandò questo messaggio: «Portate scarpe pulite per la palestra; oggi lavoriamo dentro». Sara tolse dallo zaino le scarpe infangate e ne mise un altro paio.'),
T('1. Dove si svolge l’allenamento? 2. Quale motivo del cambiamento puoi ricostruire? 3. Possiamo sapere da quanto tempo piove? 4. A che cosa si riferisce «un altro paio»? Rispondi usando il tuo strumento.'),L(5),
H('Recupero e ripasso','Spiega la differenza tra un fatto scritto e un’inferenza. Inventare un dettaglio possibile equivale a comprenderlo? In un altro giorno, usa la tabella su un breve testo scolastico e controlla una risposta con il tutor.'))
],[H('Avvio ed esempio','Un ombrello bagnato non dimostra una caduta in una fontana: può essersi bagnato sotto la pioggia o in altro modo. La chiusura della piscina è esplicita; la sorpresa di Nora resta un’inferenza discutibile.'),
H('Guidata A','1. «Chiuso per manutenzione». 2. No: sappiamo della telefonata, non del suo contenuto né di un accordo. 3. Non ci sono indizi sufficienti per attribuire con sicurezza rabbia; attendere e telefonare non la dimostrano.'),
H('Guidata B','4. Due prestiti già attivi più un nuovo libro raggiungono il limite di tre. 5. Restituire almeno uno dei libri già in prestito, se ne ha la possibilità: è una proposta coerente con la regola, non un evento narrato.'),
H('Trasferimento','1. In palestra. 2. Il campo all’aperto è molto bagnato: è una ragione plausibile del cambio, collegando le due informazioni. 3. No: non sono indicate né inizio né durata della pioggia. 4. Un altro paio di scarpe.'),
H('Criterio','Accettare formulazioni equivalenti se distinguono dato, inferenza e limite. Una risposta prudente ma motivata vale più di una risposta categorica non sostenuta.')],
'Confondere una possibilità con un fatto; cercare una parola uguale alla domanda senza integrare le informazioni; perdere il referente di un pronome. Una lettura lenta non prova una difficoltà di inferenza.',
[INV,IES],'Informazioni esplicite, inferenze semplici, integrazione di due dati e ripresa anaforica in brevi testi.','ironia complessa, testi letterari lunghi e confronto critico tra fonti.')

D+=kit('ITA02','Sintetizzare mantenendo idea centrale, nessi e limiti delle informazioni','Individuare chi fa che cosa e il risultato di un evento','Tabella scopo–informazioni–sintesi',[
P('Sintetizzare per uno scopo',H('Obiettivo e avvio','Una sintesi conserva ciò che serve a un destinatario. Prima prova: racconta in una frase l’ultima attività fatta a scuola; quale dettaglio puoi togliere senza cambiarne il senso?'),
H('Testo A · L’orto scolastico','La classe terza B voleva coltivare erbe aromatiche nel cortile. Il terreno era occupato da lavori, quindi gli studenti usarono sei cassette sul terrazzo. Divisero i turni per annaffiare. Dopo due settimane notarono che le cassette vicino al muro restavano più umide. Spostarono parte dei turni verso le cassette più esposte al sole. Alla fine del mese tutte le piante erano vive, ma non avevano ancora raccolto nulla.'),
H('Esempio per chi vuole capire le decisioni','«La terza B avviò un orto in cassette perché il terreno non era disponibile. Dopo aver osservato differenze di umidità, modificò i turni di annaffiatura. A fine mese le piante erano vive; il raccolto non era ancora iniziato». Ho mantenuto problema, decisione e risultato senza inventare un successo futuro.'),
T('Numero delle cassette e collocazione precisa possono servire a chi deve ripetere l’attività, ma non sono indispensabili per questo scopo.')),
P('Scegliere e collegare',H('Attività guidata · testo A','Completa: scopo della classe → ostacolo → prima soluzione → osservazione → nuova decisione → risultato. Usa brevi frasi, anche dettate.'),L(5),
H('Controlla questa sintesi','«La classe piantò erbe, le annaffiò e ottenne un grande raccolto». Indica un’informazione inventata e un legame importante che manca. Poi correggi il testo.'),L(3),
H('Cambiare destinatario','Se la sintesi serve a un’altra classe che vuole ripetere l’attività, quale dettaglio reinserisci? Motiva. Non devi conservare sempre gli stessi dettagli.')),
P('La tua scheda di sintesi',H('Costruisci e prova','Scegli un testo breve del kit. Scrivi prima lo scopo, poi tre informazioni essenziali e il legame fra loro. Puoi usare una tabella o una sequenza di frasi.'),
TAB(['Elemento','Appunti'],[['Destinatario e scopo',''],['Idea centrale',''],['Informazioni e nessi: perché / poi / tuttavia',''],['Limite da non perdere','']],[5.5,12.1]),L(4),
H('Checklist da personalizzare','Ho conservato l’idea centrale? I nessi sono corretti? Ho aggiunto qualcosa che il testo non dice? Il lettore capisce senza vedere il testo completo? Ho rispettato i vincoli della consegna? Scegli i controlli che ti servono.')),
P('Sintesi di un testo nuovo',H('Testo B · Il prestito degli strumenti','Il laboratorio prestava righelli e squadre senza registrare i nomi. A marzo alcuni strumenti non tornarono nell’armadio. Per capire dove fossero, gli studenti introdussero un registro con nome, oggetto e data. Nel mese successivo recuperarono quasi tutti gli strumenti mancanti. Due righelli restarono irreperibili. La classe decise di mantenere il registro, senza chiedere a ogni studente di comprare materiale nuovo.'),
T('Scrivi una sintesi di 3–4 frasi per spiegare problema, intervento e risultato. Usa la tua scheda. «Tutti gli strumenti furono recuperati» è fedele al testo?'),L(6),
H('Recupero e ripasso','Perché «quasi tutti» non equivale a «tutti»? Spiega come scegli un dettaglio da eliminare. In un giorno diverso, ricostruisci la sequenza dal tuo schema e controllala sul testo.'))
],[H('Avvio','La risposta è personale: verificare che la frase conservi l’attività centrale. Non imporre un numero fisso di parole come criterio unico di qualità.'),
H('Guidata','Scopo: coltivare erbe. Ostacolo: terreno occupato. Soluzione: cassette sul terrazzo. Osservazione: umidità diversa. Decisione: adattare i turni. Risultato: piante vive, nessun raccolto ancora. Il «grande raccolto» è inventato; mancano almeno i nessi fra ostacolo e soluzione o fra osservazione e modifica.'),
H('Destinatario diverso','Per ripetere l’attività possono servire sei cassette, terrazzo e organizzazione dei turni. Non è disponibile un protocollo agronomico completo: il testo non basta a garantire la ripetizione identica.'),
H('Trasferimento · esempio possibile','«Alcuni strumenti del laboratorio non venivano restituiti. La classe introdusse un registro dei prestiti e nel mese successivo recuperò quasi tutti gli oggetti mancanti. Due righelli non furono ritrovati; il registro venne mantenuto». Non è fedele dire che recuperarono tutto.'),
H('Criterio','Accettare sintesi diverse che mantengano problema, intervento, risultato e limite. Non aggiungere un rapporto causale dimostrato: la successione osservata suggerisce utilità del registro, non una prova sperimentale della sua efficacia.')],
'Elencare parole senza relazioni; tagliare negazioni o quantità decisive; inserire un giudizio personale; trasformare la sintesi in una copia quasi integrale. Distinguere selezione dei contenuti e formulazione scritta.',
[INV,IES],'Sintesi narrativa ed espositiva breve, selezione in base al destinatario, conservazione di nessi e limitazioni.','sintesi da più fonti, abstract disciplinari e testi argomentativi estesi.')

D+=kit('ITA03','Pianificare, scrivere e revisionare un breve testo con uno scopo riconoscibile','Formulare frasi comprensibili e distinguere un fatto da una proposta','Scaletta e checklist di revisione',[
P('Dal compito al piano',H('Obiettivo e avvio','Leggi la consegna: «Scrivi al consiglio degli studenti per proporre un angolo lettura. Spiega a che cosa serve, come organizzarlo e una difficoltà da affrontare». Quali tre contenuti non possono mancare?'),
H('Un piano prima del testo','Destinatario: consiglio degli studenti. Scopo: proporre una scelta motivata. Scaletta: bisogno → proposta → ragione ed esempio → difficoltà e soluzione → richiesta finale.'),
H('Esempio originale','«Propongo di allestire un angolo lettura nell’atrio. Potremmo usare uno scaffale già presente e libri offerti volontariamente. Sarebbe utile per leggere durante le attese; per esempio, chi arriva in anticipo avrebbe un’attività disponibile. Occorre però mantenere libero il passaggio. Chiedo quindi di verificare con la scuola uno spazio adatto prima di iniziare». La proposta resta da valutare: non afferma che tutti la desiderino.'),
H('Due revisioni diverse','Prima rivedi contenuto e ordine: il testo risponde alla consegna? Poi controlla chiarezza delle frasi, riferimenti, punteggiatura e ortografia. Puoi fare passaggi separati.')),
P('Revisionare con uno scopo',H('Bozza da migliorare','«Facciamo un angolo lettura. È bellissimo e piace a tutti. I libri li mettiamo lì. Poi qualcuno li porta. Questa cosa risolve il problema. Fatelo». Il problema e il luogo non sono precisati; il consenso di tutti non è documentato.'),
T('1. Sostituisci «piace a tutti» con una ragione o un dato che potresti verificare. 2. Rendi preciso «lì» senza inventare un’autorizzazione. 3. Aggiungi una difficoltà e una possibile soluzione.'),L(5),
H('Scrivi e rileggi un paragrafo','Usa tre o quattro frasi. Fai leggere o ascoltare la versione al tutor: chiedi che cosa ha capito e quale informazione gli manca.'),L(4)),
P('Uno strumento per scrivere',H('Costruisci la scaletta','Scegli un argomento: angolo lettura oppure cortile più ordinato. Completa le voci e prova a spiegare oralmente il piano prima di scrivere.'),
TAB(['Voce','Le mie idee'],[['Destinatario e richiesta',''],['Problema o bisogno osservato',''],['Proposta e ragione',''],['Difficoltà e risposta possibile',''],['Chiusura','']],[5.6,12]),L(3),
H('Personalizza la checklist','Scegli tre controlli: rispetto della consegna; fatti distinti da opinioni; ordine; parole di collegamento; riferimenti chiari; punteggiatura; un errore ortografico ricorrente. Segna un cambiamento concreto dopo la revisione.')),
P('Scrivere un testo nuovo',H('Trasferimento','Scrivi una proposta alla classe per uno scambio volontario di libri usati. Indica scopo, una regola, un vantaggio e una difficoltà con possibile soluzione. Non dichiarare approvazioni o adesioni non avvenute. Puoi partire da appunti o dettatura.'),
T('Usa la tua scaletta; prepara 6–8 frasi su questa pagina o su un foglio aggiunto. Rivedi prima il contenuto e poi un aspetto formale. Evidenzia una modifica.'),L(9),
H('Recupero e ripasso','Che differenza c’è tra progettare e correggere? Quale revisione ha reso il tuo testo più chiaro? In un altro giorno, confronta la prima versione con quella rivista e spiega due scelte.'))
],[H('Avvio','Devono comparire utilità, organizzazione e difficoltà. La scaletta può cambiare ordine se la proposta resta comprensibile e motivata.'),
H('Guidata · soluzioni possibili','«Potrebbe offrire una lettura durante le attese; potremmo raccogliere le preferenze della classe» evita un consenso inventato. «Proponiamo uno scaffale in uno spazio da concordare con la scuola» chiarisce il luogo senza attribuire un permesso. Difficoltà: libri smarriti; risposta: registro semplice dei prestiti.'),
H('Trasferimento · esempio di 6 frasi','«Propongo uno scambio volontario di libri usati. Ci permetterebbe di leggere titoli diversi riutilizzando libri già disponibili. Chi partecipa porta un libro in buone condizioni. Prima dello scambio concordiamo se il passaggio è definitivo o se si tratta di un prestito. Una difficoltà può essere trovare titoli adatti a tutti, perciò possiamo raccogliere prima le preferenze. Chiedo alla classe di discutere questa proposta». Non è l’unica soluzione.'),
H('Criterio e recupero','Valutare presenza dei contenuti richiesti, organizzazione, chiarezza e revisione effettiva separatamente dagli errori ortografici. Progettare decide che cosa comunicare e come ordinarlo; correggere e revisionare confrontano la bozza con lo scopo e migliorano contenuto o forma.')],
'Iniziare senza capire il destinatario; aggiungere frasi senza rivedere l’ordine; correggere solo ortografia; presentare opinioni come fatti. Se la trascrizione affatica, accogliere una prima versione orale e lavorare comunque sulla struttura.',
[IES,('Manuale locale — Italiano Speciale (DSA), indice dei materiali','../../../../../../Assets%20(markdown)/INDICE.md')],'Pianificazione, breve proposta motivata, revisione di contenuto e forma, prova scritta o dettata.','racconto esteso, generi letterari, testi argomentativi complessi e valutazione scolastica specifica.')
# Il riferimento locale è bibliografico, non un collegamento fragile esportato fuori biblioteca.
D[-1]['pages'][-1]['blocks'][-1]=T('Proposta metodologica locale consultata: Cappa et al., Italiano Speciale (DSA), Per il docente, capp. 3–5. Originale conservato nella raccolta del progetto; non incluso nei pacchetti condivisibili.')
for d in D[-2:]:d['sources']='IES, Practice Guide 1; Cappa et al., Italiano Speciale (DSA), Per il docente, capp. 3–5 (raccolta locale). Testi originali.'

D+=kit('ITA06','Riconoscere proposizioni e relazioni di coordinazione e subordinazione','Riconoscere il predicato, compresi tempi composti e verbi servili','Schema di dipendenze con parole-legame',[
P('Come si costruisce un periodo',H('Obiettivo e avvio','Confronta «Marta legge» e «Marta legge perché domani presenta un libro». Che informazione aggiunge la seconda parte?'),
H('Contenuto essenziale','Una proposizione si organizza intorno a un predicato. La principale non dipende sintatticamente da un’altra proposizione; una coordinata si collega sullo stesso piano; una subordinata dipende da una reggente. La reggente può essere anche un’altra subordinata.'),
H('Esempio spiegato','«Marta legge e prende appunti perché domani presenta un libro». Predicati: legge; prende; presenta. «Marta legge» è principale; «e prende appunti» è coordinata alla principale; «perché domani presenta un libro» è subordinata causale alla coordinata. La causa può motivare, nel significato complessivo, entrambe le attività.'),
H('Non contare parole-verbo alla cieca','«Ha letto» è un solo predicato composto. «Vuole leggere» può costituire un unico predicato con verbo servile. Per segmentare, osserva il funzionamento del gruppo verbale, non solo il numero delle forme.'),
T('Versione lineare dello schema: principale ↔ coordinata; dalla coordinata dipende una causa.')),
P('Riconoscere la relazione',
TAB(['Relazione','Esempio originale'],[['Causa: per quale motivo?','Resto dentro perché piove.'],['Tempo: quando?','Quando finisco, esco.'],['Fine: per quale scopo?','Studio per comprendere il testo.'],['Relativa: precisa un nome','Leggo il libro che mi hai prestato.']],[6,11.6]),
H('Attività guidata','A. «Quando arriva il bus, Elena sale e saluta». Sottolinea i tre predicati, separa le proposizioni e trova la principale.\nB. «Ho scelto un libro che racconta un viaggio». Individua il nome precisato dalla relativa.\nC. «Leggo per imparare nuove parole». La seconda parte indica una causa già data o uno scopo?'),L(5),
T('Nelle frasi A e B le subordinate sono esplicite; in C «per imparare» è implicita, con infinito. Non tutte le forme introdotte da «che» sono relative.')),
P('Disegnare le dipendenze',H('Costruisci il tuo strumento','Usa un riquadro per proposizione. Scrivi dentro il predicato e le parole che gli appartengono. Disponi sullo stesso livello le coordinate; collega le subordinate alla loro reggente indicando la relazione.'),
H('Prova sulla frase','«Quando finisce la lezione, Omar esce e torna a casa». Scrivi i tre riquadri e i collegamenti. La temporale fornisce il momento delle azioni della principale e della sua coordinata.'),L(7),
H('Controlla e adatta','Leggi lo schema come un periodo intero. Ogni proposizione è presente una sola volta? Hai indicato da quale proposizione dipende? Aggiungi colori solo se aiutano; usa etichette per conservare il significato anche in grigio.')),
P('Nuovi periodi da analizzare',H('Trasferimento','1. «Lina ha preparato lo zaino e aspetta perché il bus è in ritardo».\n2. «Il quaderno che hai lasciato sul banco è mio».\n3. «Apro il dizionario per cercare una parola».\nPer ciascuno: individua i predicati, trova la principale e descrivi le altre relazioni. Puoi usare lo schema.'),L(7),
H('Recupero e ripasso','Perché «ha preparato» non forma due proposizioni? La principale deve essere sempre la prima nel testo? Che differenza c’è fra causa e fine? In un giorno diverso, analizza un periodo breve del libro e confronta le etichette con quelle usate a scuola.'))
],[H('Avvio e guidata','L’informazione aggiunta motiva la lettura. A: «Quando arriva il bus» temporale; «Elena sale» principale; «e saluta» coordinata copulativa alla principale. La temporale inquadra entrambe le azioni. B: «Ho scelto un libro» principale; «che racconta un viaggio» relativa, riferita a libro. C: «Leggo» principale; «per imparare nuove parole» finale implicita.'),
H('Costruzione','«Omar esce» è principale; «e torna a casa» coordinata; «Quando finisce la lezione» temporale. Accettare la temporale collegata alla principale con annotazione che inquadra le due azioni coordinate.'),
H('Trasferimento','1. «Lina ha preparato lo zaino» principale; «e aspetta» coordinata; «perché il bus è in ritardo» causale dipendente dalla coordinata. Predicati: ha preparato, aspetta, è in ritardo.\n2. Principale discontinua: «Il quaderno … è mio»; «che hai lasciato sul banco» relativa riferita a quaderno. Predicati: è mio, hai lasciato.\n3. «Apro il dizionario» principale; «per cercare una parola» finale implicita.'),
H('Recupero','Ausiliare e participio formano un tempo composto: ha preparato è un unico predicato. La principale non coincide necessariamente con la prima proposizione. La causa spiega un motivo; il fine indica uno scopo perseguito.')],
'Contare ausiliare e participio come proposizioni separate; identificare la principale per posizione; chiamare relativa ogni proposizione con «che»; assegnare un’etichetta dalla sola congiunzione. Le convenzioni di analisi possono variare: confrontare con la grammatica adottata.',
[PER,CON],'Principale, coordinata, subordinate causali, temporali, finali e relative; forme esplicite/implicite e principale discontinua.','completive, periodo ipotetico, concessive, consecutive e dipendenze di più gradi.')

save('L01-italiano',D)
