import {S,M,L} from './contenuti-base.mjs';
export default {
 id:'M08-08',title:'Risolvere un’equazione',subject:'Matematica',area:'Algebra',intro:'Trova il numero nascosto e controlla se rende vera l’uguaglianza.',
 slides:[
 S('Preparazione','Troviamo un numero che non conosciamo','Un’equazione è un’uguaglianza che contiene un numero da trovare. Quel numero è indicato con una lettera, chiamata incognita. In questo esempio la lettera è x: cerchiamo il suo valore.',M('Il nostro esempio','3x + 5 = 20'),'Prepara foglio, penna e gli strumenti di calcolo che usi di solito. Copia l’equazione lasciando una riga libera sotto.','Il segno = dice che il valore a sinistra deve essere uguale a quello a destra. Risolvere significa trovare il numero che, messo al posto di x, rende vera questa uguaglianza.'),
 S('Esempio spiegato','Che cosa vuol dire 3x?','In algebra, 3x significa 3 × x: tre volte il numero x. Quando un numero è attaccato a una lettera, il segno × non si scrive. La moltiplicazione però c’è.',M('Due modi di scrivere la stessa cosa','3x = 3 × x','Se x fosse 2: 3 × 2 = 6'),'Indica nell’equazione “3x + 5 = 20” la moltiplicazione e l’addizione. Per ora non devi trovare x.','“Se x fosse 2” è solo un esempio per leggere 3x. Non è la soluzione della nostra equazione: 3 × 2 + 5 fa 11, non 20.'),
 S('Esempio spiegato','Leggiamo i due lati dell’uguaglianza','La parte a sinistra di = si chiama primo membro; quella a destra si chiama secondo membro. Qui il primo membro è “3x + 5” e il secondo è “20”.',M('I due membri','3x + 5     =     20'),'Sul foglio segna una piccola linea sotto ciascun membro. Il segno = deve restare tra le due parti.','Un “membro” è semplicemente uno dei due lati dell’equazione. Non devi imparare una procedura diversa: questi nomi servono a parlare delle due parti.'),
 S('Esempio spiegato','Manteniamo uguali i due lati','Se due quantità sono uguali e togliamo la stessa quantità da entrambe, restano uguali. Useremo questa idea per eliminare il +5 vicino a 3x.',M('Prima osserva con numeri noti','12 = 12','12 − 5 = 12 − 5','7 = 7'),'Guarda che −5 è scritto su entrambi i lati. Nell’equazione faremo la stessa operazione ai due membri.','Se togliessi 5 soltanto da uno dei due 12, avresti 7 = 12, che è falso. Per restare uguali, i due lati devono cambiare allo stesso modo.'),
 S('Esempio spiegato','Togliamo 5 da entrambi i membri','Vogliamo lasciare 3x senza il +5. Sottrarre 5 elimina quel +5, perché +5 −5 dà zero. Scriviamo −5 anche a destra per mantenere l’uguaglianza.',M('Operazione completa','3x + 5 = 20','3x + 5 − 5 = 20 − 5'),'Copia la seconda riga sotto l’equazione. Controlla che ci sia −5 sia a sinistra sia a destra.','Sottrarre 5 significa togliere 5. L’operazione che annulla un’aggiunta di 5 è proprio una sottrazione di 5.'),
 S('Esempio spiegato','Semplifichiamo la riga','A sinistra, +5 −5 dà zero e rimane 3x. A destra, 20 −5 dà 15. Ora sappiamo che tre volte x vale 15.',M('Dalla riga completa a quella più semplice','3x + 5 − 5 = 20 − 5','3x = 15'),'Scrivi “3x = 15” su una nuova riga, mantenendo il segno = sotto quello precedente.','Non abbiamo cambiato 3x: abbiamo solo calcolato le parti numeriche che potevamo calcolare. Usare una riga per passaggio aiuta a ritrovare il punto se ti interrompi.'),
 S('Esempio spiegato','Da tre volte x a una volta x','Per sapere quanto vale una sola x, dividiamo per 3. Dividiamo entrambi i membri per lo stesso numero: così i due lati restano uguali. Si può dividere per qualsiasi numero, tranne lo zero.',M('Divisione su entrambi i lati','3x = 15','3x ÷ 3 = 15 ÷ 3','x = 5'),'Scrivi la divisione e poi il risultato. Ora la lettera è da sola: abbiamo trovato x = 5.','3x è x + x + x. Se queste tre parti uguali valgono in tutto 15, ogni parte vale 15 ÷ 3 = 5. Puoi usare la calcolatrice se il calcolo ostacola il ragionamento.'),
 S('Esempio spiegato','Controlliamo nell’equazione iniziale','Per verificare il risultato, torniamo all’equazione da cui siamo partiti e mettiamo 5 al posto di x. Prima eseguiamo la moltiplicazione, poi l’addizione.',M('Sostituzione e controllo','3x + 5 = 20','3 × 5 + 5 = 20','15 + 5 = 20','20 = 20'),'Controlla che il valore a sinistra sia uguale a quello a destra. Qui 20 = 20 conferma la soluzione.','Non verificare soltanto l’ultima riga x = 5: devi tornare a 3x + 5 = 20. È l’equazione iniziale a dire se il numero trovato funziona.'),
 S('Prova guidata','Ora prova con z',['La lettera può cambiare: z indica ancora un numero da trovare. Qui abbiamo due volte z, poi aggiungiamo 4.','Prima vogliamo lasciare soltanto 2z a sinistra.'],M('La tua equazione','2z + 4 = 18'),'Scrivi sotto l’equazione la stessa sottrazione su entrambi i lati, in modo da eliminare +4. Non fare ancora la divisione.','Per eliminare +4, scrivi −4 a sinistra e −4 a destra. Puoi completare: 2z + 4 − 4 = 18 − 4.'),
 S('Controllo guidato','Dopo aver tolto 4','Il +4 e il −4 si annullano a sinistra. A destra 18 −4 fa 14. Ora l’equazione dice che due volte z vale 14.',M('Confronta con il tuo passaggio','2z + 4 − 4 = 18 − 4','2z = 14'),'Se il tuo passaggio è diverso, controlla prima i due −4, poi il calcolo 18 −4. Correggi il punto che non coincide.','Se avevi scritto 2z = 18, hai tolto 4 soltanto a sinistra. Scrivi l’operazione anche a destra e calcola di nuovo.'),
 S('Prova guidata','Lascia z da sola','Da “due volte z” vogliamo arrivare a “una volta z”. Scegli la divisione che lo permette e applicala anche al numero 14.',M('Parti da qui','2z = 14'),'Scrivi la divisione su entrambi i membri e poi il valore di z.','Dividi per 2: 2z ÷ 2 = 14 ÷ 2. A sinistra resta z. A destra puoi calcolare 14 ÷ 2 con il tuo strumento abituale.'),
 S('Controllo guidato','Verifica il numero trovato','La divisione dà z = 7. Mettiamo 7 al posto di z nell’equazione iniziale. I due lati valgono 18, quindi il risultato funziona.',M('Il controllo completo','2z + 4 = 18','2 × 7 + 4 = 18','14 + 4 = 18','18 = 18'),'Confronta il tuo risultato con questo controllo. Indica dove compare il 7 che ha sostituito z.','Se avevi trovato un numero diverso, sostituiscilo nell’originale. Se i lati non coincidono, torna alla prima riga in cui il tuo lavoro è diverso dal modello.'),
 S('Compito nuovo','Questa volta c’è una sottrazione','Qui dopo quattro volte y togliamo 7. Per lasciare 4y da solo, scegli l’operazione che annulla −7. Poi continua fino a trovare y.',M('Compito nuovo','4y − 7 = 13'),'Risolvi sul foglio, una riga per volta, e verifica nell’equazione iniziale. Vai avanti quando vuoi confrontare il procedimento.','Per annullare −7 devi aggiungere 7, perché −7 +7 dà zero. Aggiungi 7 a entrambi i membri; poi chiediti come passare da quattro volte y a una volta y.'),
 S('Controllo','Confronta le operazioni','Aggiungiamo 7 da entrambe le parti. Poi dividiamo entrambi i membri per 4. In questo modo la lettera rimane da sola.',M('Soluzione del compito nuovo','4y − 7 + 7 = 13 + 7','4y = 20','4y ÷ 4 = 20 ÷ 4','y = 5'),'Confronta una riga alla volta. Se trovi una differenza, controlla l’operazione scelta e il suo calcolo prima di copiare il risultato.','Il fatto che anche qui la soluzione sia 5 non dipende dal nome della lettera. Dipende dai numeri di questa equazione: ogni nuova equazione va risolta e controllata.'),
 S('Controllo','Controlla anche la sottrazione finale','Sostituiamo y con 5 nell’originale. Prima 4 ×5 dà 20. Poi 20 −7 dà 13, uguale al secondo membro.',M('Verifica del compito nuovo','4y − 7 = 13','4 × 5 − 7 = 13','20 − 7 = 13','13 = 13'),'Confronta questa verifica con la tua. Se avevi sommato 7 anche qui, torna all’originale: nella verifica rimane il suo −7.','Le operazioni usate per risolvere non sostituiscono l’equazione da verificare. Il controllo usa sempre la riga iniziale, con tutti i suoi segni.'),
 S('Controllo','Un errore da riconoscere','Da 3x +5 =20 non possiamo passare a 3x =20 togliendo il +5 solo a sinistra. Nel nuovo passaggio il lato destro dovrebbe diventare 15.',M('Il passaggio da correggere','3x + 5 = 20','ERRORE: 3x = 20','CORREZIONE: 3x + 5 − 5 = 20 − 5'),'Spiega sul foglio o a voce quale operazione mancava a destra.','Riguarda l’esempio numerico: 12 −5 non è uguale a 12. Per lasciare uguali i lati devi togliere la stessa quantità anche al secondo.'),
 S('Ripresa a casa','Usa una riga per ogni passaggio',['Questo metodo funziona con equazioni come quelle che hai visto. C’è una lettera moltiplicata per un numero. Poi c’è un numero aggiunto o tolto.','Alcune equazioni sono diverse: hanno parentesi, frazioni o la lettera da tutte e due le parti. Per quelle, riguarda prima la spiegazione dell’insegnante.'],L('Il tuo promemoria','Copia l’equazione e leggi le operazioni vicino alla lettera.','Annulla l’aggiunta o la sottrazione con la stessa operazione sui due membri.','Dividi entrambi i membri per il numero che moltiplica la lettera.','Sostituisci la soluzione nell’originale e confronta i due valori.'),'Scegli un’equazione dello stesso tipo dal compito. Nel Menu puoi stampare esempio, prove e promemoria per casa.','Puoi tenere aperto il modello. Puoi usare calcolatrice, tavole o formulario, se li usi già a scuola. Quello che conta è scegliere i passaggi e controllarli. Non serve sapere tutto a memoria.')
 ],
 coach:{goal:'Osservare scelta dell’operazione, applicazione ai due membri e verifica nell’originale. Gli esempi riguardano ax+b=c con a positivo e soluzioni intere; non costituiscono un corso completo sulle equazioni.',prepare:'Verificare il significato di moltiplicazione e divisione con un esempio concreto. Se questi prerequisiti non sono disponibili, lavorarci prima di proseguire. Non introdurre la regola “sposta e cambia segno” come scorciatoia priva di spiegazione.',observe:'Far indicare l’operazione sul membro sinistro e su quello destro. Chiedere “Perché questa operazione?”. Distinguere un errore nella scelta da un errore nel calcolo.',adaptations:[['Lettura e allineamento — possibile difficoltà con dislessia o disgrafia','Perdita di un segno, salti di riga, cifre difficili da rileggere.','Fornire l’equazione già scritta, una riga per passaggio e spazio ampio. Leggere a voce i segni. Verificare che la copia resti coerente prima di interpretare un errore come concettuale.'],['Calcolo — possibile difficoltà con discalculia','Operazione scelta correttamente, ma calcoli o fatti aritmetici rallentano il procedimento.','Lasciare calcolatrice e tavole già in uso. Far spiegare quale calcolo inserire. Controllare separatamente il ragionamento sui membri e l’esecuzione aritmetica.'],['Ortografia — possibile disortografia','Una spiegazione scritta contiene errori di parole ma il procedimento è corretto.','Accogliere anche la spiegazione orale; non usare l’ortografia come indicatore della comprensione dell’uguaglianza.']],sources:[0,3]},
 print:{modelTitle:'Equazione commentata',model:['3x + 5 = 20. La scrittura 3x significa 3 × x.','1. Tolgo 5 da entrambi i membri: 3x + 5 − 5 = 20 − 5.','2. Calcolo: 3x = 15.','3. Divido entrambi per 3: 3x ÷ 3 = 15 ÷ 3. Quindi x = 5.','4. Verifico nell’originale: 3 × 5 + 5 = 15 + 5 = 20. Il secondo membro è 20: coincidono.','Fare la stessa operazione ai due membri mantiene l’uguaglianza; qui dividiamo per un numero diverso da zero.'],practice:[['Prova guidata','2z + 4 = 18\nPrima annulla +4 sui due membri. Poi dividi entrambi per il numero che moltiplica z. Verifica nell’originale.'],['Compito nuovo','4y − 7 = 13\nScegli come annullare −7. Applica l’operazione ai due membri, continua e verifica.']],answers:['2z + 4 − 4 = 18 − 4 → 2z = 14 → 2z ÷ 2 = 14 ÷ 2 → z = 7. Verifica: 2 × 7 + 4 = 18.','4y − 7 + 7 = 13 + 7 → 4y = 20 → 4y ÷ 4 = 20 ÷ 4 → y = 5. Verifica: 4 × 5 − 7 = 13.','Se il risultato non funziona, controlla una riga alla volta: operazione scelta, presenza sui due membri, calcolo.'],home:['Una riga per passaggio; tieni sempre l’equazione iniziale.','Scegli l’operazione che annulla il numero aggiunto o sottratto.','Applica ogni operazione a entrambi i membri.','Quando la lettera è da sola, verifica nell’originale.']}
};
