import {S,T,L,G,fable,adventure} from './contenuti-base.mjs';
const primaDellaMappa=()=>[
 S('Preparazione','Scegli parole che conservano l’idea','Osserva la frase “La favola è un racconto breve”. Per ricordare che tipo di testo è, teniamo “racconto”. Per ricordare la sua lunghezza, teniamo “breve”. Sono parole chiave perché ci aiutano a ricostruire l’informazione.',T('Dalla frase alle parole utili','La favola è un racconto breve.\n\nTipo di testo → racconto\nLunghezza → breve'),'Scrivi “racconto breve” sul foglio. Poi prova a usarlo per dire la frase completa.','Scegliere parole chiave non vuol dire eliminare tutte le altre parole per sempre. Nella mappa concettuale useremo parole anche sulle frecce; nella mappa mentale le aggiungeremo a voce per spiegare.'),
 S('Preparazione','Distingui il gruppo dal suo dettaglio','In questa frase, “personaggi” è il gruppo di cui si parla. Le parole successive dicono qualcosa di più su quel gruppo. Prima di disegnare la mappa, cerca l’informazione da conservare.',T('La frase da esaminare','I personaggi sono spesso animali che parlano e si comportano come persone.'),'Sul foglio scrivi “Personaggi”. Accanto, annota poche parole che dicano chi sono spesso. Tieni davanti la frase e poi avanza per controllare.','Chiediti: che tipo di personaggi descrive questa frase? C’è una parola che evita di dire “tutti” o “sempre”? Conservala nella tua nota.'),
 S('Controllo della preparazione','“Spesso animali” mantiene una precisazione','Una nota possibile è “Personaggi → spesso animali”. “Personaggi” indica il gruppo; “spesso animali” aggiunge un dettaglio. La parola “spesso” conserva il significato del testo.',T('Frase e nota','I personaggi sono spesso animali che parlano e si comportano come persone.\n\nPersonaggi → spesso animali'),'Confronta la tua nota. Se hai scritto solo “animali”, aggiungi “spesso”. Potrai aggiungere in seguito anche il dettaglio su come parlano e agiscono.','Non serve mettere tutte le informazioni in una sola etichetta. Puoi aggiungere un dettaglio dopo l’altro, lasciandoli collegati al gruppo a cui si riferiscono.')
];
const coachBase={prepare:'Tenere disponibile il testo mentre si costruisce la mappa. Leggerlo insieme e verificare “morale” come insegnamento sui comportamenti. La disposizione proposta è un esempio, non uno schema da imporre a tutti i testi.',adaptations:[['Leggere e scegliere informazioni — possibile difficoltà con dislessia','Il carico di lettura impedisce di ritrovare la frase a cui collegare un nodo.','Leggere ad alta voce o usare la sintesi vocale abituale, una frase per volta. Lasciare il testo visibile e far indicare quale informazione viene rappresentata.'],['Scrivere e disporre i nodi — possibile difficoltà con disgrafia','Lo studente sa spiegare i collegamenti ma perde spazio o non riesce a rileggere le etichette.','Offrire riquadri già pronti o cartellini mobili. Chiedere allo studente di scegliere e collegare; non sostituirsi nella decisione sul significato.'],['Ortografia — possibile difficoltà con disortografia','La ricerca della grafia corretta interrompe ogni scelta concettuale.','Consentire copia del termine dal testo o etichette predisposte. Controllare prima i collegamenti e poi, separatamente, l’ortografia.'],['Sovraccarico visivo — difficoltà trasversale','Molti rami rendono difficile ritrovare il punto di partenza.','Costruire un ramo alla volta, distanziare le parti e verificare se lo studente riesce a spiegare un percorso. La difficoltà non implica un DSA specifico.']],sources:[0,1,3,4]};
const conceptual={
 id:'MC-01',title:'Mappa concettuale: la favola',subject:'Italiano',area:'Mappe concettuali',mapType:'Mappa concettuale',intro:'Collega idee con parole che spieghino la relazione.',
 slides:[
 S('Preparazione','Una mappa per spiegare i collegamenti',['Una mappa concettuale mostra idee e relazioni. Le idee sono scritte nei riquadri; le parole sulle frecce spiegano come si collegano.','Costruiremo una piccola mappa sulla favola. Ti serviranno il testo, un foglio e una penna. Puoi usare un foglio in orizzontale per avere spazio.'],T('Che cosa imparerai a fare','Leggere due riquadri e una freccia come una frase che ha senso.'),'Scrivi sul foglio “Mappa concettuale — la favola”. Lascia spazio sotto.','Un concetto è un’idea che vogliamo rappresentare, come “favola” o “personaggi”. Non serve mettere ogni parola del testo in un riquadro.'),
 S('Preparazione','Prima capiamo il testo','Leggi o ascolta questo testo. La morale è l’insegnamento che una storia suggerisce sul modo di comportarsi. Può essere scritto oppure ricavato dagli eventi.',T('Il testo di partenza',fable),'Indica nel testo che cosa si dice sulla lunghezza, sui personaggi e sulla morale. Per ora non disegnare i collegamenti.','“Spesso” non significa “sempre”: molte favole hanno animali come personaggi, ma non tutte. Questa differenza deve restare riconoscibile nella mappa.'),
 ...primaDellaMappa(),
 S('Esempio spiegato','Scegliamo a quale domanda rispondere','Una domanda aiuta a decidere quali informazioni mettere nella mappa. Qui vogliamo spiegare le caratteristiche generali della favola, senza raccontare una storia particolare.',T('La domanda della nostra mappa','Quali caratteristiche ha una favola?'),'Scrivi questa domanda sopra lo spazio della mappa. Ti servirà per controllare se i collegamenti rispondono al compito.','Se la domanda fosse “Che cosa accade nella favola letta oggi?”, servirebbero invece gli eventi di quella storia. Prima di scegliere i riquadri, chiarisci quale domanda hai davanti.'),
 S('Esempio spiegato','Partiamo dall’idea principale','Il testo comincia con “La favola è un racconto breve”. La prima idea è “favola”: sarà il punto da cui partire per leggere gli altri collegamenti.',G('concept',0),'Disegna un riquadro con la parola “Favola” nella parte alta del foglio.','Un riquadro aiuta a vedere dove finisce un’idea e comincia un’altra. Basta una forma semplice: non serve decorarlo.'),
 S('Esempio spiegato','La freccia deve dire qualcosa','Dal testo ricaviamo due idee, “favola” e “racconto”. La parola “è” scritta sulla freccia esprime il collegamento. Leggendo tutto otteniamo: “La favola è un racconto”.',G('concept',1),'Sotto “Favola”, disegna “Racconto”. Traccia una freccia dal primo riquadro al secondo e scrivi “è” vicino alla freccia.','Una freccia senza parole non spiega se un’idea è un esempio, una parte o una causa dell’altra. Qui “è” permette di leggere una frase precisa.'),
 S('Esempio spiegato','Aggiungiamo il dettaglio “breve”','La stessa frase del testo dice che il racconto è breve. Aggiungiamo questa informazione sotto “Racconto”, con un’altra freccia e un’altra parola “è”.',G('concept',2),'Disegna “Breve” sotto “Racconto” e collega con “è”. Leggi: “Il racconto è breve”.','Puoi scegliere anche un solo riquadro “Racconto breve”. Qui li separiamo per imparare a esprimere una relazione. Una mappa non deve avere un numero obbligatorio di riquadri.'),
 S('Esempio spiegato','Costruiamo il ramo dei personaggi','Il testo dice: “I personaggi sono spesso animali”. Dal riquadro “Favola” parte un nuovo collegamento: la favola ha personaggi. Da “Personaggi” continuiamo con “sono spesso” verso “Animali”.',G('concept',4),'Aggiungi questo ramo accanto a quello sul racconto. Mantieni la parola “spesso” sulla seconda freccia.','Un ramo è una parte della mappa che parte da un punto e sviluppa un’informazione. Se scrivessimo soltanto “sono animali”, renderemmo l’affermazione troppo generale.'),
 S('Esempio spiegato','Colleghiamo morale e insegnamento','La storia contiene una morale, cioè un insegnamento sui comportamenti. Aggiungiamo due relazioni: “La favola contiene una morale” e “La morale esprime un insegnamento”.',G('concept',6),'Aggiungi il ramo della morale. Poi leggilo come due frasi complete.','Una morale può essere lasciata da ricavare al lettore: “contiene” non significa che nel libro ci sia sempre una frase finale già scritta. Il testo di partenza lo precisa.'),
 S('Controllo dell’esempio','Leggiamo la mappa completa','Ora puoi seguire tre percorsi. Ogni volta parti da “Favola” e leggi riquadri e parole sulle frecce. La mappa riassume alcune caratteristiche: il testo resta disponibile per i dettagli.',G('concept',6),'Scegli un ramo e spiegalo a voce. Controlla nel testo: “favola = racconto breve; personaggi spesso animali; morale = insegnamento sui comportamenti”.','Se riesci solo a elencare “favola, personaggi, animali”, prova a inserire le parole delle frecce: “La favola ha personaggi. I personaggi sono spesso animali”.'),
 S('Prova guidata','Ricostruisci un collegamento sul foglio','Ora prova a costruire tu il ramo della morale senza copiare la mappa completa. Hai qui la frase del testo che ti serve e le idee da collegare.',T('La frase da usare','La storia contiene un insegnamento sui comportamenti: questo insegnamento si chiama morale.\n\nIdee disponibili: Favola — Morale — Insegnamento.'),'Su una parte libera del foglio disegna i tre riquadri. Scrivi sulle due frecce parole che permettano di leggere frasi sensate.','Puoi iniziare con “La favola contiene …”. Poi chiediti che cosa esprime la morale. Le parole-legame non devono essere indovinate a memoria: devono dire una relazione coerente con il testo.'),
 S('Controllo guidato','Controlla le tue due frasi','Un possibile collegamento è questo. Se hai scritto “La favola propone una morale” oppure “La morale è un insegnamento”, discutine il significato: conta che la relazione sia chiara e coerente.',T('Un ramo possibile','Favola → contiene → Morale\nMorale → esprime → Insegnamento'),'Leggi il tuo ramo, includendo le parole sulle frecce. Se una frase resta incompleta, modifica la parola-legame.','“Favola → morale → insegnamento”, senza parole sulle frecce, lascia al lettore il compito di indovinare i collegamenti. Aggiungi ciò che diresti a voce tra le idee.'),
 S('Compito nuovo','Costruisci una mappa da un testo diverso',['Ora cambia l’argomento. La domanda è: “Quali caratteristiche ha il racconto d’avventura?”.','Leggi il testo e scegli tre aspetti da rappresentare: impresa, protagonista e luoghi. Puoi tenere il testo davanti mentre lavori.'],T('Testo per il compito nuovo',adventure),'Scrivi in alto la domanda e disegna il primo riquadro “Racconto d’avventura”.','Un’impresa è un’azione impegnativa da portare a termine. Il protagonista è il personaggio principale. Un ostacolo è qualcosa che rende difficile proseguire.'),
 S('Compito nuovo','Ora collega le idee scelte','Parti da “Racconto d’avventura” e costruisci i tre rami. Per ogni freccia, cerca parole che facciano leggere una frase completa. Aggiungi almeno un dettaglio per ramo.',T('Tieni a disposizione il testo',adventure),'Disegna la mappa sul foglio. Quando hai finito, leggi ogni collegamento e confrontalo con il testo. Avanza per vedere un possibile controllo.','Per il primo ramo puoi chiederti: che cosa racconta il racconto d’avventura? Un’impresa. Com’è l’impresa? Rischiosa. Usa lo stesso ragionamento sugli altri due aspetti.'),
 S('Controllo','Confronta le relazioni della tua mappa','Queste sono relazioni possibili, non un’unica disposizione obbligatoria. Nella tua mappa possono esserci riquadri uniti o separati, purché il significato sia chiaro.',L('Frasi da ritrovare','Il racconto d’avventura racconta un’impresa rischiosa.','Il racconto d’avventura ha un protagonista che affronta pericoli e ostacoli.','Il racconto d’avventura può svolgersi in luoghi lontani o sconosciuti.'),'Controlla un ramo alla volta. Conserva parole come “può”: il testo non dice che i luoghi siano sempre sconosciuti.','Per questa prova abbiamo scelto tre aspetti. Il testo parla anche dell’attesa creata dagli eventi: puoi aggiungere un quarto ramo se serve alla tua spiegazione, senza riempire la mappa di dettagli inutili.'),
 S('Ripresa a casa','Parti dalla domanda, poi costruisci un ramo',['Sul compito di casa scrivi prima a quale domanda vuoi rispondere. Leggi un breve tratto di testo e costruisci un ramo; poi passa al successivo.','Una mappa funziona se ti aiuta a spiegare collegamenti e a ritrovare informazioni. Se non riesci a leggerla, riduci o riorganizza quel punto.'],L('Il metodo da riprendere','Scegli la domanda e tieni davanti il testo.','Individua poche idee utili alla domanda.','Collegale con parole che formino frasi.','Controlla ogni relazione nel testo e prova a spiegarla.'),'Prova su un breve paragrafo del tuo libro. Nel Menu trovi la scheda da stampare con esempio e traccia.','Una mappa concettuale può avere anche collegamenti tra rami diversi. Aggiungili quando sai spiegare una relazione utile: non servono per forza in una prima mappa piccola.')
 ],
 coach:{...coachBase,goal:'Osservare se le parole-legame esprimono relazioni controllabili nel testo. Non confondere la qualità della mappa con la somiglianza grafica al modello.',observe:'Far leggere una proposizione completa per ramo e indicare la frase del testo che la sostiene. Il collegamento “sono spesso” conserva una qualificazione importante. La mappa semplificata non rappresenta ogni dettaglio né introduce obbligatoriamente legami trasversali.'},
 print:{modelTitle:'Mappa concettuale — esempio',visual:G('concept',6),model:['Domanda: quali caratteristiche ha una favola?',fable,'Leggi ogni coppia di riquadri con la parola sulla freccia: “La favola è un racconto”. Poi: “Il racconto è breve”.'],practice:[['Prova guidata','Ricostruisci il ramo Favola — Morale — Insegnamento. Scegli parole sulle frecce che formino frasi coerenti: la favola contiene una morale, cioè un insegnamento.'],['Compito nuovo',adventure+'\nDomanda: quali caratteristiche ha il racconto d’avventura? Disegna tre rami: impresa, protagonista, luoghi. Aggiungi parole-legame e dettagli.']],answers:['Ramo guidato: Favola → contiene → Morale → esprime → Insegnamento.','Avventura: racconta un’impresa rischiosa; ha un protagonista che affronta pericoli e ostacoli; può svolgersi in luoghi lontani o sconosciuti.','Sono possibili altre disposizioni. Controlla che ogni collegamento si possa leggere come una frase e sia sostenuto dal testo.'],home:['Scrivi la domanda a cui vuoi rispondere.','Scegli idee pertinenti e collega un ramo alla volta.','Metti parole sulle frecce; conserva precisazioni come “spesso” o “può”.','Rileggi nel testo e spiega i collegamenti a voce.']}
};
const mental={
 id:'MM-01',title:'Mappa mentale: la favola',subject:'Italiano',area:'Mappe mentali',mapType:'Mappa mentale',intro:'Metti un tema al centro e organizza le informazioni in rami.',
 slides:[
 S('Preparazione','Una mappa per organizzare le informazioni',['Una mappa mentale parte da un tema al centro. I rami raccolgono aspetti del tema, come cartelline in cui mettere informazioni vicine per significato.','Costruiremo una mappa sulla favola con parole brevi ma comprensibili. Prepara un foglio in orizzontale e una penna. I colori sono facoltativi.'],T('Che cosa imparerai a fare','Trovare il ramo giusto e usarlo per ricordare e spiegare un’informazione.'),'Scrivi sul foglio “Mappa mentale — la favola” e lascia libero il centro.','Qui i rami raggruppano informazioni. Non occorre scrivere parole su ogni collegamento come nella mappa concettuale; quando spieghi, però, devi saper dire che cosa significano le parole che hai scelto.'),
 S('Preparazione','Leggiamo prima di disegnare','Leggi o ascolta questo testo. La morale è l’insegnamento sui comportamenti suggerito dalla storia. Può essere dichiarato oppure lasciato da ricavare al lettore.',T('Il testo di partenza',fable),'Trova nel testo un’informazione sulla storia, una sui personaggi e una sul messaggio.','Il messaggio è ciò che la storia vuole farci capire. In questo testo coincide con la morale. Prima di usare una parola nella mappa, verifica di sapere che cosa significa.'),
 ...primaDellaMappa(),
 S('Esempio spiegato','Mettiamo il tema al centro','Il tema è “Favola”. Scriviamolo al centro: da qui partiranno i rami. Il centro deve farti capire subito di che cosa parla la mappa.',G('mental',0),'Scrivi “Favola” al centro del foglio e circonda la parola con una forma semplice.','Non serve un disegno elaborato. Se ti aiuta puoi aggiungere una piccola immagine, ma la parola deve restare leggibile e riconoscibile.'),
 S('Esempio spiegato','Il primo ramo raccoglie la storia','Nel testo leggiamo che la favola è un racconto breve. Apriamo un ramo “Storia”: è il nome della categoria in cui metteremo le caratteristiche del racconto.',G('mental',1),'Dal centro traccia una linea verso “Storia”. Lascia spazio dopo questa parola per aggiungere un dettaglio.','Una categoria è un gruppo di informazioni che hanno qualcosa in comune. “Storia” raggruppa qui le informazioni sul racconto; gli animali andranno invece nel ramo dei personaggi.'),
 S('Esempio spiegato','Aggiungiamo una parola che ci faccia ricordare','Sul ramo “Storia” aggiungiamo “Breve”. È una parola chiave: poche lettere ci aiutano a ritrovare l’informazione “la favola è un racconto breve”.',G('mental',2),'Aggiungi “Breve” alla fine di un piccolo ramo che parte da “Storia”. Poi spiega a voce che cosa significa.','Una parola chiave funziona se per te richiama un’informazione precisa. Se “breve” da sola non basta, puoi scrivere “racconto breve”. La mappa non deve diventare un indovinello.'),
 S('Esempio spiegato','Un secondo ramo per i personaggi','Ora creiamo il ramo “Personaggi”. Il testo dice che sono spesso animali: usiamo proprio le parole “Spesso animali”, perché non tutte le favole devono avere animali.',G('mental',4),'Aggiungi “Personaggi” partendo dal centro e poi il dettaglio “Spesso animali”.','Dal tema centrale partono i rami principali. I dettagli partono dal ramo a cui appartengono: “Spesso animali” deve essere vicino a “Personaggi”, non vicino a “Storia”.'),
 S('Esempio spiegato','Un terzo ramo per il messaggio','Il ramo “Messaggio” raccoglie l’insegnamento della favola. Aggiungiamo “Morale”, il nome che il testo usa per quell’insegnamento.',G('mental',6),'Aggiungi “Messaggio” e poi “Morale”. Spiega a voce: “La morale è l’insegnamento sui comportamenti suggerito dalla storia”.','Se il termine “morale” ti resta poco chiaro, nella tua mappa puoi scrivere “Morale: insegnamento”. Scegli parole che ti permettano di spiegare, non solo di copiare.'),
 S('Controllo dell’esempio','Usiamo la mappa completa','Dal centro puoi scegliere tre rami. Per parlare della lunghezza vai a “Storia”. Per dire chi compare vai a “Personaggi”. Per spiegare l’insegnamento vai a “Messaggio”.',G('mental',6),'Scegli un ramo e usalo per spiegare una caratteristica della favola. Poi controlla il significato: racconto breve; personaggi spesso animali; morale come insegnamento.','La mappa raccoglie una selezione di informazioni. Se il compito richiede anche come si ricava la morale, aggiungi un dettaglio a quel ramo usando il testo.'),
 S('Prova guidata','Scegli in quale ramo mettere un dettaglio','Adesso aggiungiamo un’informazione che nel primo modello non avevamo rappresentato: nel testo gli animali parlano e si comportano come persone.',T('Il dettaglio da collocare','“I personaggi sono spesso animali che parlano e si comportano come persone”.\n\nRami disponibili: Storia — Personaggi — Messaggio.'),'Scegli il ramo adatto. Aggiungi sul foglio il dettaglio “Parlano e agiscono come persone” nel punto che hai scelto. Avanza per confrontarlo.','Chiediti a chi si riferisce il dettaglio. Parla degli animali che fanno da personaggi: per questo va nello stesso ramo, non in quello sulla lunghezza della storia.'),
 S('Controllo guidato','Controlla perché hai scelto quel ramo','Il dettaglio appartiene ai personaggi. Una possibile organizzazione parte da “Personaggi”, continua con “Spesso animali” e aggiunge “Parlano e agiscono come persone”.',T('Il collegamento da controllare','Personaggi → Spesso animali → Parlano e agiscono come persone'),'Guarda il tuo foglio e spiega perché quelle informazioni stanno insieme. Se serve, sposta il dettaglio nel ramo dei personaggi.','Non basta che una parola “stia bene” graficamente. Deve stare vicino alle informazioni a cui si riferisce, altrimenti quando studi potresti collegarla all’idea sbagliata.'),
 S('Compito nuovo','Organizza un altro argomento',['Ora il tema è “Racconto d’avventura”. Leggi il testo e scegli tre categorie per organizzarlo: impresa, protagonista e luoghi.','Il protagonista è il personaggio principale. Un’impresa è un’azione impegnativa da portare a termine.'],T('Testo per il compito nuovo',adventure),'Scrivi il tema al centro di un foglio nuovo. Da lì fai partire i tre rami con i nomi delle categorie.','Puoi modificare la posizione dei rami per avere spazio. La posizione sulla pagina non cambia il significato; cambierebbe invece il significato se un dettaglio finisse nella categoria sbagliata.'),
 S('Compito nuovo','Scegli dettagli che ti aiutino a spiegare','Per ciascuna categoria scegli una o poche parole dal testo. Tieni le precisazioni che evitano errori: i luoghi possono essere lontani o sconosciuti, non lo sono obbligatoriamente.',T('Tieni davanti il testo',adventure),'Aggiungi almeno un dettaglio per ramo e prova a spiegare la mappa. Avanza quando vuoi confrontare l’organizzazione.','Per “Impresa” puoi scegliere “rischiosa”. Cerca poi che cosa fa il protagonista e quali caratteristiche possono avere i luoghi.'),
 S('Controllo','Confronta i gruppi di informazioni','Questa è un’organizzazione possibile. La tua può avere altre parole o una disposizione diversa: controlla che tu riesca a ritrovare le informazioni del testo.',L('Tre rami possibili','Impresa → rischiosa.','Protagonista → affronta pericoli e ostacoli.','Luoghi → possono essere lontani o sconosciuti.'),'Scegli una tua parola chiave e spiega l’intera informazione che richiama. Se non ci riesci, rendi l’etichetta più chiara.','Il testo dice anche che gli eventi creano attesa. Se serve al tuo compito, puoi aggiungere un ramo “Eventi” con “creano attesa”. Non è necessario far entrare tutto in tre rami.'),
 S('Ripresa a casa','Controlla se la mappa ti fa ritrovare le idee',['A casa comincia da un testo breve e tienilo davanti. Scrivi il tema al centro, scegli i rami e aggiungi i dettagli uno alla volta.','Poi usa la mappa per spiegare. Se una parola non ti ricorda niente, riaprila al testo e sostituiscila con una più chiara.'],L('Il tuo promemoria','Tema al centro.','Un ramo per ciascun aspetto scelto.','Dettagli vicino all’aspetto a cui si riferiscono.','Una spiegazione a voce per controllare se le parole aiutano.'),'Prova con un breve paragrafo del tuo libro. Nel Menu puoi stampare esempio, prova e promemoria per casa.','Colori e piccoli disegni possono aiutare a distinguere i rami, ma non sono obbligatori. Prima controlla significato e leggibilità: la mappa deve servirti per studiare.')
 ],
 coach:{...coachBase,goal:'Osservare se lo studente raggruppa informazioni per significato e usa le parole chiave per ricostruire una spiegazione. Non valutare decorazione, quantità di colori o somiglianza estetica al modello.',observe:'Chiedere “Perché questo dettaglio sta in questo ramo?” e “Quale frase ti ricorda questa parola?”. Distinguere mappa mentale come organizzazione radiale da mappa concettuale con relazioni esplicite. Il formato mentale qui proposto è un adattamento editoriale, non una prescrizione universale.'},
 print:{modelTitle:'Mappa mentale — esempio',visual:G('mental',6),model:[fable,'Dal centro scegli un ramo. Poi spiega che cosa ti ricorda la parola: “Breve” → la favola è un racconto breve.'],practice:[['Prova guidata','Aggiungi il dettaglio “Parlano e agiscono come persone” al ramo adatto: Storia, Personaggi o Messaggio. Spiega la tua scelta.'],['Compito nuovo',adventure+'\nMetti al centro “Racconto d’avventura”. Costruisci i rami Impresa, Protagonista, Luoghi e aggiungi un dettaglio per ciascuno.']],answers:['Il dettaglio va vicino a “Spesso animali” nel ramo “Personaggi”: descrive proprio quei personaggi.','Impresa → rischiosa; Protagonista → affronta pericoli e ostacoli; Luoghi → possono essere lontani o sconosciuti.','La disposizione può cambiare. Controlla il significato dei gruppi e la tua capacità di spiegare le parole chiave.'],home:['Leggi il testo e scrivi il tema al centro.','Scegli categorie utili e apri un ramo per ciascuna.','Aggiungi dettagli comprensibili, anche con più di una parola.','Usa i rami per spiegare e torna al testo per controllare.']}
};
export default [conceptual,mental];
