import {S,T,L} from './contenuti-base.mjs';
const poem='D’oro si veste\nil colle al mattino.';
const guided='Dorme il villaggio\nsotto un manto di neve.';
const fresh='Tra i rami sussurra\nil vento della sera.';
export default {
 id:'M02-02',title:'Fare la parafrasi',subject:'Italiano',area:'Poesia',intro:'Riscrivi una poesia con parole più comuni, mantenendo il significato.',
 slides:[
 S('Preparazione','Riscrivere, mantenendo il significato',['Una poesia può usare un ordine insolito delle parole o espressioni che non vanno prese alla lettera. La parafrasi serve a riscrivere quel testo con parole più comuni.','Scriverai in prosa: frasi come quelle di un racconto, senza dover rispettare le righe della poesia. Alla fine controllerai di non aver cambiato il significato.'],L('Prepara','Il testo da riscrivere','Un foglio e una penna','Un dizionario o l’aiuto di chi ti accompagna'),'Scrivi sul foglio il titolo “Parafrasi”. Lascia spazio per il testo originale e per la tua riscrittura.','Non devi inventare un’altra storia. Immagina di spiegare le stesse informazioni a una persona che fatica a capire le parole della poesia.'),
 S('Esempio spiegato','Leggiamo due versi',['Queste due righe di poesia sono due versi. Le useremo come esempio. Il colle è una collina.','Qui “oro” richiama il colore giallo della luce del sole. Questa informazione ci aiuta a capire l’immagine scelta nella poesia.'],T('Testo originale',poem),'Leggi o ascolta i due versi una volta. Per ora cerca soltanto di immaginare la scena.','Puoi chiedere all’adulto di leggere. Immagina una collina al mattino: il sole la illumina. Non serve imparare i versi a memoria.'),
 S('Esempio spiegato','Troviamo di chi si parla','In questa frase, il colle è ciò di cui si dice che “si veste”. In grammatica è il soggetto. Nella poesia arriva dopo il verbo, ma possiamo metterlo all’inizio per rendere la frase più facile da seguire.',T('Versi da osservare',poem),'Indica le parole “il colle” nel testo. Sono le parole che metteremo all’inizio.','Chiediti: che cosa “si veste”? La risposta è “il colle”. In altre frasi questa domanda va adattata al verbo: qui serve a seguire questo esempio.'),
 S('Esempio spiegato','Rimettiamo in ordine le parole','Mettiamo prima “Il colle”, poi “si veste”, poi “d’oro” e infine “al mattino”. Abbiamo cambiato l’ordine; non abbiamo ancora spiegato l’immagine dell’oro.',T('Prima e dopo','D’oro si veste / il colle al mattino.\n\nIl colle si veste d’oro al mattino.'),'Segui con il dito le quattro parti della frase riordinata. Ritrova ciascuna parte nei versi.','Le parole “al mattino” dicono quando succede la scena. Anche nella parafrasi devono esserci. Puoi spostare le parole, ma tienile tutte.'),
 S('Esempio spiegato','Spieghiamo l’immagine dell’oro','“Si veste d’oro” è un’espressione figurata. Un’espressione figurata usa un’immagine per dire un’altra cosa. Qui l’immagine è un vestito d’oro. Vuol dire che la luce dorata del sole illumina il colle.',T('Espressione e significato','Il colle si veste d’oro.\n\nIl colle è illuminato dalla luce dorata del sole.'),'Leggi il significato. Immagina se descrive la stessa scena dei versi.','Per capire un’immagine, guarda le parole vicine. Chiediti: che scena descrive la poesia? Anche il dizionario aiuta. Leggi tutte le definizioni e scegli quella giusta per la scena.'),
 S('Esempio spiegato','Ricomponiamo una frase completa','Ora mettiamo insieme due cose: il significato dell’immagine e il momento della giornata. Mettiamo “al mattino” all’inizio. Così si capisce subito quando il colle è illuminato.',T('Originale e parafrasi',poem+'\n\nAl mattino il colle è illuminato dalla luce dorata del sole.'),'Scrivi la parafrasi sotto i versi. Confronta: ci sono ancora il colle, la luce dorata e il mattino?','La parafrasi può essere più lunga dei versi. Le parole in più servono a spiegare. Aggiungi solo spiegazioni. “Il colle è bello” è un’opinione: nei versi non c’è.'),
 S('Prova guidata','Quale frase mantiene lo stesso significato?','Prima di scrivere da solo, guarda queste due frasi. Puoi usare parole diverse dai versi. Le informazioni, però, devono restare le stesse.',T('Originale e due possibilità',poem+'\n\nA. Al mattino la luce dorata del sole illumina il colle.\nB. Al tramonto la luce dorata del sole illumina il colle.'),'Sul foglio scrivi A oppure B. Indica nei versi la parola che ti ha aiutato a scegliere. Avanza per controllare.','Cerca l’informazione sul momento della giornata. Devi poterla ritrovare anche nella frase che scegli.'),
 S('Controllo guidato','La parola “mattino” decide il confronto','La frase A mantiene il momento della giornata indicato dal testo. La B lo cambia: “tramonto” è il momento in cui il sole scende sotto l’orizzonte, non il mattino.',T('Confronto con il testo',poem+'\n\nA. Al mattino la luce dorata del sole illumina il colle.'),'Se avevi scelto B, correggi soltanto l’indicazione del tempo. Hai usato una parola del testo per controllare il significato.','Due frasi possono sembrare simili e dire cose diverse. Nella parafrasi tieni anche i piccoli dettagli, come il momento o il luogo.'),
 S('Prova guidata','Proviamo con un altro testo',['Adesso userai gli stessi passaggi su questi versi. “Manto” può indicare una copertura; qui è la neve che copre il villaggio.','Quando il testo dice che il villaggio “dorme”, descrive la quiete del luogo: non significa che le case dormano davvero.'],T('La tua prova',guided),'Copia i versi sul foglio, oppure usa una copia già pronta. Lascia una riga sotto per la parafrasi.','Se copiare ti fa perdere il filo, chiedi un testo già stampato. Il lavoro da imparare qui è capire e riscrivere il significato.'),
 S('Prova guidata','Mettiamo il villaggio all’inizio','Questa volta le parole da mettere all’inizio sono “Il villaggio”. Dopo vengono “dorme” e “sotto un manto di neve”. Prima di spiegare le immagini, rendiamo chiaro l’ordine.',T('Testo da riordinare',guided),'Completa sul foglio: “Il villaggio …”. Usa tutte le informazioni dei due versi.','La frase riordinata è “Il villaggio dorme sotto un manto di neve”. Se avevi scritto un ordine diverso, controlla che il significato sia lo stesso.'),
 S('Prova guidata','Sostituisci le immagini con il significato','Ora trasforma “dorme” in un’espressione che dica che il villaggio è quieto. Trasforma “sotto un manto di neve” in parole che dicano che è coperto di neve.',T('Informazioni da mantenere','Il villaggio dorme sotto un manto di neve.\n\n“Dorme” → è quieto.\n“Manto di neve” → copertura di neve.'),'Scrivi una frase completa sul villaggio. Puoi iniziare con “Il villaggio è …”.','Prova a unire “è quieto” e “coperto di neve”. Non aggiungere dettagli come l’ora o il numero delle case: i versi non li indicano.'),
 S('Controllo guidato','Confronta il significato, non le singole parole','Questa è una possibile parafrasi. Anche “Il villaggio è tranquillo e la neve lo ricopre” mantiene il significato. Non è necessario aver scelto le stesse parole del modello.',T('Una soluzione possibile','Il villaggio è quieto e coperto di neve.'),'Controlla la tua frase: parla del villaggio, della quiete e della neve che lo copre? Se manca un’informazione, aggiungila.','Se hai scritto soltanto “C’è la neve”, manca la quiete del villaggio. Torna all’espressione “dorme” e inserisci anche il suo significato.'),
 S('Compito nuovo','Adesso scegli tu i passaggi',['Usa questo testo nuovo. “Sussurra” significa “parla a voce molto bassa”; qui descrive il rumore leggero del vento tra i rami.','Puoi tenere aperti il testo e questa spiegazione mentre lavori.'],T('Nuovi versi',fresh),'Sul foglio scrivi la parafrasi. Prima riordina la frase; poi spiega “sussurra”. Vai avanti quando vuoi confrontare il tuo lavoro.','Chiediti: che cosa produce il suono? Dove? In quale momento? Nel testo trovi “il vento”, “tra i rami” e “della sera”. Tienile tutte nella parafrasi.'),
 S('Controllo','Leggiamo una soluzione possibile','Il soggetto è “il vento della sera”. L’espressione “sussurra” viene spiegata come un rumore leggero. L’indicazione “tra i rami” rimane nella frase.',T('Originale e parafrasi',fresh+'\n\nIl vento della sera produce un rumore leggero tra i rami.'),'Confronta la tua parafrasi con i versi. Se hai scritto “soffia piano tra i rami”, chiediti se risulta chiaro anche il suono leggero descritto dal testo.','Puoi correggere solo il punto che manca. Per esempio, a “Il vento passa tra i rami” puoi aggiungere “la sera, producendo un rumore leggero”.'),
 S('Controllo','Riconosci un’aggiunta non presente nel testo','“Il vento spaventoso spezza i rami” cambia la scena: nei versi non si parla né di paura né di rami spezzati. Nella parafrasi spieghiamo le parole del testo, senza inventare altri eventi.',T('Il testo a cui tornare',fresh),'Rileggi la tua frase. Cerca eventuali informazioni che non puoi ritrovare o ricavare dai versi. Toglile o discutile con chi ti accompagna.','Non tutto ciò che immagini leggendo deve entrare nella parafrasi. Le tue impressioni possono servire in un commento personale, che è un lavoro diverso.'),
 S('Ripresa a casa','Riprendi il metodo sul tuo compito',['A casa affronta pochi versi per volta. Tieni sempre davanti l’originale mentre riscrivi.','Se un’immagine resta poco chiara, segnala la parola e chiedi aiuto sul suo significato prima di proseguire.'],L('La sequenza da seguire','Leggi o ascolta i versi e chiarisci le parole difficili.','Ricostruisci una frase con un ordine che riesci a seguire.','Spiega le immagini usando il contesto.','Confronta ogni informazione con il testo originale.'),'Scegli i primi versi del compito assegnato e applica la sequenza. Nel Menu trovi la scheda da stampare.','Per capire se il metodo funziona, scegli una parola della tua parafrasi. Spiega perché l’hai scelta. Se ritrovi nei versi la parola che te l’ha fatta scegliere, stai lavorando bene.')
 ],
 coach:{goal:'Osservare se lo studente ricostruisce e conserva il significato, distinguendo parafrasi e commento. Non richiedere una formulazione identica al modello.',prepare:'Usare i testi originali di questo prototipo, letti insieme. Chiarire prima il lessico necessario. I versi sono stati scritti per l’esercitazione; non sono citazioni di un autore.',observe:'Chiedere “Quale parola dei versi ti ha fatto scrivere questo?”. Se lo studente non risponde, tornare al punto del testo e modellare un solo collegamento, poi proporne un altro allo studente.',adaptations:[['Lettura dei versi — possibile difficoltà con dislessia','Lettura lenta o errori che fanno perdere la scena.','Offrire lettura dell’adulto o sintesi vocale già abituale e mantenere il testo visibile. Verificare se lo studente individua le informazioni ascoltate.'],['Scrittura — possibile difficoltà con disgrafia o disortografia','Il significato è spiegato oralmente, ma la scrittura assorbe tutto lo sforzo.','Accettare inizialmente una parafrasi orale o scritta dall’adulto sotto dettatura. Separare il controllo del significato da quello ortografico; mantenere disponibili gli strumenti consueti.']],sources:[0,3,4]},
 print:{modelTitle:'Esempio commentato',model:[poem,'1. Individuo il colle: è ciò di cui si dice che “si veste”.','2. Riordino: “Il colle si veste d’oro al mattino”.','3. Spiego l’immagine: il colle è illuminato dalla luce dorata del sole.','4. Scrivo: “Al mattino il colle è illuminato dalla luce dorata del sole”.','5. Controllo che ci siano il colle, la luce dorata e il mattino.'],practice:[['Prova guidata',guided+'\nQui “dorme” indica quiete e “manto” indica copertura. Riordina la frase e spiega le due immagini.'],['Compito nuovo',fresh+'\nQui “sussurra” descrive il rumore leggero del vento. Riscrivi mantenendo chi, dove e quando.']],answers:['Prova guidata: “Il villaggio è quieto e coperto di neve”.','Compito nuovo: “Il vento della sera produce un rumore leggero tra i rami”.','Sono possibili parole diverse. Controlla le informazioni, non la corrispondenza parola per parola.'],home:['Leggi pochi versi e chiarisci il lessico.','Riordina la frase; spiega le immagini usando il contesto.','Confronta la riscrittura con l’originale e togli le aggiunte non giustificate.']}
};
